project:
  type: book
  output-dir: docs
book:
  title: DocuScope
  subtitle: Corpus Analysis & Concordancer
  sidebar:
    title: DocuScope CA
    logo: images/docuscope-logo.png
    style: docked
    background: light
    collapse-level: 1
    tools:
    - icon: github
      href: https://github.com/browndw/docuscope-ca-online
    - icon: globe2
      href: https://docuscope-ca.eberly.cmu.edu/
  chapters:
    - index.qmd
    - part: DocuScope CA Apps
      chapters:
        - guide/load-corpus.qmd
        - guide/token-frequencies.qmd
        - guide/tag-frequencies.qmd
        - guide/ngrams.qmd
        - guide/compare-corpora.qmd
        - guide/compare-corpus-parts.qmd
        - guide/collocations.qmd
        - guide/kwic.qmd
        - guide/advanced-plotting.qmd
        - guide/single-document.qmd
        - guide/assisted-plotting.qmd
        - guide/assisted-analysis.qmd
        - guide/download-corpus.qmd
        - guide/download-tagged-files.qmd
    - part: Tagsets
      chapters:
        - tagsets/model-comparison.qmd
        - tagsets/claws7-tags.qmd
        - tagsets/docuscope-fd-tags.qmd
        - tagsets/docuscope-cd-tags.qmd
    - part: Datasets
      chapters:
         - datasets/micusp.qmd
         - datasets/bawe.qmd
         - datasets/elsevier.qmd
         - datasets/hape.qmd
    - part: Vignettes
      chapters:
         - vignettes/external-corpus.qmd
         - vignettes/results-to-paper.qmd
    - part: The DocuScope Project
      chapters:
         - about/kaufer-ishizaki.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    link-external-icon: false
    toc: true
    toc-depth: 4
