project:
  type: book
  output-dir: docs
book:
  title: DocuScope
  author: David Brown
  sidebar:
    logo: images/docuscope-logo.png
    style: docked
    background: light
    collapse-level: 1
  chapters:
    - index.qmd
    - part: DocuScope CA Apps
      chapters:
        - guide/load-corpus.qmd
        - guide/token-frequencies.qmd
        - guide/tag-frequencies.qmd
        - guide/ngrams.qmd
        - guide/compare-corpora.qmd
        - guide/compare-corpus-parts.qmd
        - guide/collocations.qmd
        - guide/kwic.qmd
        - guide/advanced-plotting.qmd
        - guide/single-document.qmd
        - guide/assisted-plotting.qmd
        - guide/assisted-analysis.qmd
        - guide/download-corpus.qmd
        - guide/download-tagged-files.qmd
    - part: About the DocuScope Project
      chapters:
         - about/kaufer-ishizaki.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    link-external-icon: false
    toc: true
    toc-depth: 4
