# DocuScope Tags (Common Dictionary) {.unnumbered}

{{< iconify material-symbols:construction >}} Under construction.

The Common Dictionary contains eight primary categories.

| Category     | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|--------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Actors       | Actors describe the topical focus of a text or its "aboutness". As the metaphor of "actors" suggests, this category accounts for who or what occupies the stage in a text. Of course, in a longer text, a writer will bring a variety of actors on and off the stage, as topics shift from one to another. However, a text's goals and audience will shape the overall composition of a cast. Consider, for example, how the Actors in an ecomomics paper, a literary analysis paper and an economics paper might be balanced somewhat differently. |
| Citation     | Citation categories relate to the ways in which writers attribute assertions, claims or messages to other sources. Those attributions can assign more authority to a source (e.g., 'the report shows...') or open up space for alternative conclusions (e.g., 'the report suggests...').                                                                                                                                                                                                                                                            |
| Confidence   | Confidence language signals a writer's attitude toward statements and claims. Think for example about the difference between "it is clear..." versus "it is possible...". The first signals a greater degree of certainty while the latter acknoweldges the potential for alternative interpretations. Note that niether makes the assertion any more or less objective or factual. In fact, most writing requires us to constantly evaluate and modulate our expressions of confidence.                                                            |
| Organization | Organization refers to the ways in which writers link phrases, sentences, events and claims. Two types of Organization are highlighted: Narrative and Reasoning. We tend to associate Narrative with the telling of stories, particularly in fiction. However, Narrative is also used in academic and professional writing, as well. Think, for example, about how we might organize a lab report or parts of a Methods section. We would likely need to report a clear sequence of events, which would require Narrative.                          |
| Planning     | The language of planning points forward and can orient readers toward future states or goals.                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| Sentiment    | The emotional or affective content of a piece of writing is often measured by Sentiment. Is that emotional content largely postive? Or negative?                                                                                                                                                                                                                                                                                                                                                                                                    |
| Signposting  | Signposts are words or phrases that help readers navigate a text, marking structure, transitions or the carrying out of expected rheorical functions (like the posing of a research question, for example).                                                                                                                                                                                                                                                                                                                                         |
| Stance       | Stance is related to the "voice" or "tone" of a text and signals writers' commitments and judgments. Stance can encompass a wide range of features, but these categories focus on the ways in which writers can advertise a more assertive or emphatic stance, and the ways they pull back and moderate their stance.                                                                                                                                                                                                                               |
The specific tags are then organized into that basic taxonomy.

| **Tag**                             | **Description**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | **Examples**                        |
|-------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------|
| Actors: Abstractions                | Abstract Actors are more common when communicating to a specialist rather than a general audience. This kind of language can invoke disciplinary specialization or general abstraction, including words with Greek or Latinate suffixes like -logy, -graph, -ability, -esia, -ization (e.g., 'sociology'; 'polygraph'; 'adoptability'; 'kinesia') but also words that are conceptual (e.g., 'automate'; 'factor'; 'paradigm').                                                                                                       | *model*, *information*, *level*     |
| Actors: First Person                | First Person is active when we forground ourselves, often using pronouns like 'I' or 'we'. First Person Actors are more frequent in interactive contexts like speech and texting, but First Person Actors serve imporant functions in academic writing, as well.                                                                                                                                                                                                                                                                     | *I*, *our*, *we are*                |
| Actors: People                      | When People are prioritized as Actors, communication foregrounds characters, groups (e.g., 'women', 'men', 'children', 'teenagers'), individuals and particular communities.                                                                                                                                                                                                                                                                                                                                                         | *people*, *individuals*, *she*      |
| Actors: Public Entities             | When Actors are Public Entities, they reference concepts from public language, media, the language of authority, institutions, and responsibility.                                                                                                                                                                                                                                                                                                                                                                                   | *national*, *society*, *government* |
| Citation: Authority                 | Authoritative Citation language aligns your text with your source. It advocates a speaker’s or an author’s point of view and reinforces the authority of that point of view. That authority might be located in an external source; however, it might also be assigned to the results or findings of study.                                                                                                                                                                                                                          | *found that*, *shows that*          |
| Citation: Controversy               | Controversy Citation language acknowledges the source is part of a controversy and may not share the full story.                                                                                                                                                                                                                                                                                                                                                                                                                     | *argues that*, *claims*             |
| Citation: Neutral                   | Neutral Citation language focuses on the “facts” the source provides rather than investigating its value or persuasiveness. It can be seen as a dispassionate kind of relationship to a source.                                                                                                                                                                                                                                                                                                                                      | *according to*, *discussed*         |
| Confidence: Hedged                  | Hedged Confidence language signals moderate or flexible certainty and openness to other points of view.                                                                                                                                                                                                                                                                                                                                                                                                                              | *can be*, *may be*                  |
| Confidence: High                    | High confidence language signals high certainty that would withstand intense debate.                                                                                                                                                                                                                                                                                                                                                                                                                                                 | *it is*, *clearly*                  |
| Organization: Narrative             | Narrative is used most often to organize events by time (e.g., 'before'; 'after'), but can also be used to sequence them (e.g., 'first of all'; 'finally').                                                                                                                                                                                                                                                                                                                                                                          | *during the*, *after*               |
| Organization: Reasoning             | Reasoning directs readers from statement to statement by either opening up inferences or blocking inferences. This language can be constructive, meaning that it can connect ideas to form new pathways (e.g., therefore; it stands to reason that). It can also give possible pathways that depend upon contingencies (e.g., 'if this happens, then that can happen'; 'most likely'). Reasoning language can also shut down new pathways by drawing clearly oppositional lines (e.g., 'it is not the case that'; 'refute'; 'deny'). | *results*, *analysis*               |
| Planning: Future                    | Referencing future actions, states, or desires.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | *will*, *proposed*                  |
| Planning: Strategy                  | This dimension is active when the text structures activism, advantage-seeking, game-playing cognition, plans and goal-seeking.                                                                                                                                                                                                                                                                                                                                                                                                       | *design*, *decision*                |
| Sentiment: Negative                 | Referencing dimensions of negativity, including negative acts, emotions, relations, and values.                                                                                                                                                                                                                                                                                                                                                                                                                                      | *corrupted*, *confrontation*        |
| Sentiment: Positive                 | References positive across a variety of dimensions, including actions, emotions, relations, and values.                                                                                                                                                                                                                                                                                                                                                                                                                              | *health*, *opportunity*             |
| Signposting: Academic Writing Moves | Academic Writing Moves are typically associated with STEM-oriented research literature. They can refer to how the research was conducted (i.e., how the writer collected and analyzed data). They can also signal results at a descriptive level, as well as analyze and interpret the meaning and overall significance of the reported findings.                                                                                                                                                                                    | *this study*, *method of*           |
| Signposting: Metadiscourse          | Metadiscourse functions as traffic signs, orienting and directing readers and can include references to oneself as a writer (e.g., 'I argue'), the audience (e.g., 'we can see that'), or the writing itself (e.g., 'in this paper').                                                                                                                                                                                                                                                                                                | *or*, *however*                     |
| Stance: Emphatic                    | An emphatic stance shows a higher level of force and stronger commitments, judgments or engagements.                                                                                                                                                                                                                                                                                                                                                                                                                                 | *very*, *actually*                  |
| Stance: Moderated                   | A moderated stance shows a less intense level of commitment or force, judgments or engagements.                                                                                                                                                                                                                                                                                                                                                                                                                                      | *slightly*, *partially*             |
