<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Collocational Patterns in Human and AI Writing – DocuScope</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../vignettes/external-corpus.html" rel="next">
<link href="../vignettes/workflow-passive-constructions.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3d73c9dd21032f6a02c0f397ec6d8864.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../vignettes/workflow-academic-levels.html">Vignettes</a></li><li class="breadcrumb-item"><a href="../vignettes/workflow-hape-collocations.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Collocational Patterns in Human and AI Writing</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../images/docuscope-logo.png" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../images/docuscope-logo.png" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">DocuScope CA</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/browndw/docuscope-ca-online" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
    <a href="https://docuscope-ca.eberly.cmu.edu/" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-globe2"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Getting Started</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">DocuScope CA Apps</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../guide/load-corpus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewbox="0 -960 960 960" width="20px" fill="#434343"><path d="M479.5-144q-140.5 0-238-41.85T144-288v-384q0-60 98-102t237.5-42q139.5 0 238 42T816-672v384q0 60.3-98 102.15Q620-144 479.5-144Zm.47-456Q566-600 646-621.5t98-50.5q-18-28-98.5-50t-165.53-22Q394-744 313.5-722T216-672q17 29 96.5 50.5T479.97-600Zm.03 192q42 0 80-4.5t71.5-12.5q33.5-8 62-20.5T744-474v-109q-24.25 13.22-53.62 23.61Q661-549 627.17-542.15q-33.83 6.85-71 10.5Q519-528 479.5-528t-77.11-3.65q-37.62-3.65-71-10.5Q298-549 268.5-559.5 239-570 216-583v109q22.41 15.94 50.21 28.47Q294-433 327.5-425q33.5 8 72 12.5T480-408Zm.32 192q43.32 0 88.05-6.4 44.73-6.39 82.4-16.9 37.67-10.5 63.09-23.75Q739.29-276.3 744-290v-101q-24.25 13.22-53.62 23.61Q661-357 627.17-350.15q-33.83 6.85-71 10.5Q519-336 479.5-336t-77.11-3.65q-37.62-3.65-71-10.5Q298-357 268.5-367.5 239-378 216-391v103q5 13 30.5 26t63 23q37.5 10 82.5 16.5t88.32 6.5Z"></path></svg> Manage Corpus Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../guide/token-frequencies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewbox="0 -960 960 960" width="20px" fill="#434343"><path d="M312-96q-33 0-52.5-19.5T240-168v-480q0-33 19.5-52.5T312-720h480q33 0 52.5 19.5T864-648v480q0 33-19.5 52.5T792-96H312Zm0-72h204v-132H312v132Zm276 0h204v-132H588v132ZM96-240v-552.45q0-32.55 19.5-52.05t52.05-19.5H720v72H168v552H96Zm216-132h204v-132H312v132Zm276 0h204v-132H588v132ZM312-576h480v-72H312v72Z"></path></svg> Token Frequencies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../guide/tag-frequencies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewbox="0 -960 960 960" width="20px" fill="#434343"><path d="M312-96q-33 0-52.5-19.5T240-168v-480q0-33 19.5-52.5T312-720h480q33 0 52.5 19.5T864-648v480q0 33-19.5 52.5T792-96H312Zm0-72h204v-132H312v132Zm276 0h204v-132H588v132ZM96-240v-552.45q0-32.55 19.5-52.05t52.05-19.5H720v72H168v552H96Zm216-132h204v-132H312v132Zm276 0h204v-132H588v132ZM312-576h480v-72H312v72Z"></path></svg> Tag Frequencies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../guide/ngrams.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewbox="0 -960 960 960" width="20px" fill="#434343"><path d="M312-96q-33 0-52.5-19.5T240-168v-480q0-33 19.5-52.5T312-720h480q33 0 52.5 19.5T864-648v480q0 33-19.5 52.5T792-96H312Zm0-72h204v-132H312v132Zm276 0h204v-132H588v132ZM96-240v-552.45q0-32.55 19.5-52.05t52.05-19.5H720v72H168v552H96Zm216-132h204v-132H312v132Zm276 0h204v-132H588v132ZM312-576h480v-72H312v72Z"></path></svg> N-grams &amp; Clusters</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../guide/compare-corpora.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewbox="0 -960 960 960" width="20px" fill="#434343"><path d="m336-168-51-51 105-105H96v-72h294L285-501l51-51 192 192-192 192Zm288-240L432-600l192-192 51 51-105 105h294v72H570l105 105-51 51Z"></path></svg> Compare Corpora</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../guide/compare-corpus-parts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewbox="0 -960 960 960" width="20px" fill="#434343"><path d="m336-168-51-51 105-105H96v-72h294L285-501l51-51 192 192-192 192Zm288-240L432-600l192-192 51 51-105 105h294v72H570l105 105-51 51Z"></path></svg> Compare Corpus Parts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../guide/collocations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewbox="0 -960 960 960" width="20px" fill="#434343"><path d="M227.78-96Q173-96 134.5-134.72T96-228.22q0-54.78 38.66-93.28 38.67-38.5 93.37-38.5 16.97 0 33.28 4.5Q277.61-351 292-343l152-152.42V-605q-42.24-12.32-69.12-46.92-26.88-34.6-26.88-80.1 0-54.98 38.72-93.48 38.72-38.5 93.5-38.5t93.28 38.6q38.5 38.6 38.5 93.21 0 45.19-26.88 79.99T516-605v109.55L667.71-343q14.78-8 31.04-12.5Q715-360 731.97-360q54.7 0 93.37 38.72Q864-282.56 864-227.78t-38.72 93.28Q786.56-96 731.78-96t-93.28-38.66Q600-173.33 600-228.03q0-16.97 4.5-33.28Q609-277.61 617-292L480-429 343-292q8 14.28 12.5 30.46 4.5 16.19 4.5 33.32 0 55.22-38.72 93.72T227.78-96ZM732-168q25 0 42.5-17.5T792-228q0-25-17.5-42.5T732-288q-25 0-42.5 17.5T672-228q0 25 17.5 42.5T732-168ZM480-672q25 0 42.5-17.5T540-732q0-25-17.5-42.5T480-792q-25 0-42.5 17.5T420-732q0 25 17.5 42.5T480-672ZM228-168q25 0 42.5-17.5T288-228q0-25-17.5-42.5T228-288q-25 0-42.5 17.5T168-228q0 25 17.5 42.5T228-168Z"></path></svg> Collocations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../guide/kwic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewbox="0 -960 960 960" width="20px" fill="#434343"><path d="M227.78-96Q173-96 134.5-134.72T96-228.22q0-54.78 38.66-93.28 38.67-38.5 93.37-38.5 16.97 0 33.28 4.5Q277.61-351 292-343l152-152.42V-605q-42.24-12.32-69.12-46.92-26.88-34.6-26.88-80.1 0-54.98 38.72-93.48 38.72-38.5 93.5-38.5t93.28 38.6q38.5 38.6 38.5 93.21 0 45.19-26.88 79.99T516-605v109.55L667.71-343q14.78-8 31.04-12.5Q715-360 731.97-360q54.7 0 93.37 38.72Q864-282.56 864-227.78t-38.72 93.28Q786.56-96 731.78-96t-93.28-38.66Q600-173.33 600-228.03q0-16.97 4.5-33.28Q609-277.61 617-292L480-429 343-292q8 14.28 12.5 30.46 4.5 16.19 4.5 33.32 0 55.22-38.72 93.72T227.78-96ZM732-168q25 0 42.5-17.5T792-228q0-25-17.5-42.5T732-288q-25 0-42.5 17.5T672-228q0 25 17.5 42.5T732-168ZM480-672q25 0 42.5-17.5T540-732q0-25-17.5-42.5T480-792q-25 0-42.5 17.5T420-732q0 25 17.5 42.5T480-672ZM228-168q25 0 42.5-17.5T288-228q0-25-17.5-42.5T228-288q-25 0-42.5 17.5T168-228q0 25 17.5 42.5T228-168Z"></path></svg> Key Words in Context</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../guide/advanced-plotting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewbox="0 -960 960 960" width="20px" fill="#434343"><path d="m147-192-51-51 288-288 157 157 65-73-222-219-237 237-51-51 288-288 270 267 156-176 54 47-159 179 162 161-51 50-159-157-113 127-160-160-237 238Z"></path></svg> Advanced Plotting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../guide/single-document.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewbox="0 -960 960 960" width="20px" fill="#434343"><path d="m592-168 72 72H264q-29.7 0-50.85-21.15Q192-138.3 192-168v-624q0-29.7 21.15-50.85Q234.3-864 264-864h312l192 192v476q0 36-5.5 54T746-116L553-309q-15 10-34 14.5t-39 4.5q-60 0-102-42t-42-102q0-60 42-102t102-42q60 0 102 42t42 102q0 20-5 39.5T604-360l92 92v-374L546-792H264v624h328ZM480.21-362Q510-362 531-383.21t21-51Q552-464 530.79-485t-51-21Q450-506 429-484.79t-21 51Q408-404 429.21-383t51 21Zm-.21-82Zm0 0Z"></path></svg> Single Documents</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../guide/assisted-plotting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewbox="0 -960 960 960" width="20px" fill="#434343"><path d="M192-384q-40 0-68-28t-28-68q0-40 28-68t68-28v-72q0-29.7 21.15-50.85Q234.3-720 264-720h120q0-40 28-68t68-28q40 0 68 28t28 68h120q29.7 0 50.85 21.15Q768-677.7 768-648v72q40 0 68 28t28 68q0 40-28 68t-68 28v168q0 29.7-21.16 50.85Q725.68-144 695.96-144H263.72Q234-144 213-165.15T192-216v-168Zm168-72q20 0 34-14t14-34q0-20-14-34t-34-14q-20 0-34 14t-14 34q0 20 14 34t34 14Zm228 0q20 0 34-14t14-34q0-20-14-34t-34-14q-20 0-34 14t-14 34q0 20 14 34t34 14ZM336-312h288v-72H336v72Zm-72 96h432v-432H264v432Zm216-216Z"></path></svg> AI-Assisted Plotting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../guide/assisted-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewbox="0 -960 960 960" width="20px" fill="#434343"><path d="M192-384q-40 0-68-28t-28-68q0-40 28-68t68-28v-72q0-29.7 21.15-50.85Q234.3-720 264-720h120q0-40 28-68t68-28q40 0 68 28t28 68h120q29.7 0 50.85 21.15Q768-677.7 768-648v72q40 0 68 28t28 68q0 40-28 68t-68 28v168q0 29.7-21.16 50.85Q725.68-144 695.96-144H263.72Q234-144 213-165.15T192-216v-168Zm168-72q20 0 34-14t14-34q0-20-14-34t-34-14q-20 0-34 14t-14 34q0 20 14 34t34 14Zm228 0q20 0 34-14t14-34q0-20-14-34t-34-14q-20 0-34 14t-14 34q0 20 14 34t34 14ZM336-312h288v-72H336v72Zm-72 96h432v-432H264v432Zm216-216Z"></path></svg> AI-Assisted Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../guide/download-corpus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewbox="0 -960 960 960" width="20px" fill="#434343"><path d="M480-336 288-528l51-51 105 105v-342h72v342l105-105 51 51-192 192ZM263.72-192Q234-192 213-213.15T192-264v-72h72v72h432v-72h72v72q0 29.7-21.16 50.85Q725.68-192 695.96-192H263.72Z"></path></svg> Download Corpus Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../guide/download-tagged-files.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewbox="0 -960 960 960" width="20px" fill="#434343"><path d="M480-336 288-528l51-51 105 105v-342h72v342l105-105 51 51-192 192ZM263.72-192Q234-192 213-213.15T192-264v-72h72v72h432v-72h72v72q0 29.7-21.16 50.85Q725.68-192 695.96-192H263.72Z"></path></svg> Download Tagged Files</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Tagsets</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tagsets/model-comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model Comparison</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tagsets/claws7-tags.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part-of-Speech Tags</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tagsets/docuscope-fd-tags.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DocuScope Tags (Full Dictionary)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tagsets/docuscope-cd-tags.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DocuScope Tags (Common Dictionary)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Datasets</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../datasets/micusp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MICUSP</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../datasets/bawe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">BAWE</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../datasets/elsevier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Elsevier</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../datasets/hape.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HAP-E</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Vignettes</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/workflow-academic-levels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Rhetorical Patterns Across Academic Levels</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/workflow-passive-constructions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Passive Constructions Across Disciplines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/workflow-hape-collocations.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Collocational Patterns in Human and AI Writing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/external-corpus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Creating and Using an External Corpus File</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/results-to-paper.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Turning Your Results Into a Research Paper</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">The DocuScope Project</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about/kaufer-ishizaki.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">History and background</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#use-case" id="toc-use-case" class="nav-link active" data-scroll-target="#use-case"><span class="header-section-number">3.1</span> Use Case</a></li>
  <li><a href="#step-1-load-the-corpus" id="toc-step-1-load-the-corpus" class="nav-link" data-scroll-target="#step-1-load-the-corpus"><span class="header-section-number">3.2</span> Step 1: Load the Corpus</a>
  <ul>
  <li><a href="#process-document-metadata" id="toc-process-document-metadata" class="nav-link" data-scroll-target="#process-document-metadata"><span class="header-section-number">3.2.1</span> Process Document Metadata</a></li>
  </ul></li>
  <li><a href="#step-2-identify-a-target-word-with-token-frequencies" id="toc-step-2-identify-a-target-word-with-token-frequencies" class="nav-link" data-scroll-target="#step-2-identify-a-target-word-with-token-frequencies"><span class="header-section-number">3.3</span> Step 2: Identify a Target Word with Token Frequencies</a></li>
  <li><a href="#step-3-compute-collocations" id="toc-step-3-compute-collocations" class="nav-link" data-scroll-target="#step-3-compute-collocations"><span class="header-section-number">3.4</span> Step 3: Compute Collocations</a>
  <ul>
  <li><a href="#understanding-npmi" id="toc-understanding-npmi" class="nav-link" data-scroll-target="#understanding-npmi"><span class="header-section-number">3.4.1</span> Understanding NPMI</a></li>
  <li><a href="#reading-the-collocations-table" id="toc-reading-the-collocations-table" class="nav-link" data-scroll-target="#reading-the-collocations-table"><span class="header-section-number">3.4.2</span> Reading the Collocations Table</a></li>
  </ul></li>
  <li><a href="#step-4-examine-concordance-lines-with-kwic" id="toc-step-4-examine-concordance-lines-with-kwic" class="nav-link" data-scroll-target="#step-4-examine-concordance-lines-with-kwic"><span class="header-section-number">3.5</span> Step 4: Examine Concordance Lines with KWIC</a>
  <ul>
  <li><a href="#patterns-in-gpt-4-academic-writing" id="toc-patterns-in-gpt-4-academic-writing" class="nav-link" data-scroll-target="#patterns-in-gpt-4-academic-writing"><span class="header-section-number">3.5.1</span> Patterns in GPT-4 Academic Writing</a></li>
  <li><a href="#patterns-in-human-academic-writing" id="toc-patterns-in-human-academic-writing" class="nav-link" data-scroll-target="#patterns-in-human-academic-writing"><span class="header-section-number">3.5.2</span> Patterns in Human Academic Writing</a></li>
  <li><a href="#patterns-in-llama-tvmovie-script-writing" id="toc-patterns-in-llama-tvmovie-script-writing" class="nav-link" data-scroll-target="#patterns-in-llama-tvmovie-script-writing"><span class="header-section-number">3.5.3</span> Patterns in Llama TV/Movie Script Writing</a></li>
  </ul></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation"><span class="header-section-number">3.6</span> Interpretation</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../vignettes/workflow-academic-levels.html">Vignettes</a></li><li class="breadcrumb-item"><a href="../vignettes/workflow-hape-collocations.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Collocational Patterns in Human and AI Writing</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Collocational Patterns in Human and AI Writing</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="use-case" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="use-case"><span class="header-section-number">3.1</span> Use Case</h2>
<p>A researcher in digital writing studies wants to investigate whether large language models (LLMs) produce distinctive word associations when compared to human writers — and whether those patterns vary by genre. Specifically: does a common evaluative adjective like <em>important</em> collocate with the same words across GPT-4-generated, Llama-generated, and human texts? And does genre (academic, news, spoken, TV/movie scripts) modulate those patterns?</p>
<p>This vignette introduces two tools for moving from raw frequency data to interpretable linguistic patterns:</p>
<ul>
<li>The <strong>Collocations</strong> tool, which uses point-wise mutual information (PMI) statistics to identify words that co-occur with a node word more often than chance would predict</li>
<li>The <strong>KWIC</strong> (Key Words in Context) tool, which presents concordance lines — aligned rows showing each occurrence of a word surrounded by its left and right context — enabling qualitative exploration of how a word is actually used</li>
</ul>
<p><strong>Corpus used:</strong> <code>H_HAPE_mini</code> (Internal corpora, Large Dictionary)</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>HAP-E Mini</strong> corpus contains a curated, balanced sample drawn from the Human-AI Parallel English (HAP-E) Corpus <span class="citation" data-cites="reinhart2025llms">(<a href="#ref-reinhart2025llms" role="doc-biblioref">Reinhart et al. 2025</a>)</span>. The full HAP-E corpus pairs human-authored texts with multiple LLM continuations of the same prompts. The mini version retains three author groups across six text types. See the <a href="../datasets/hape.html">HAP-E dataset page</a> for full details.</p>
</div>
</div>
<hr>
</section>
<section id="step-1-load-the-corpus" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="step-1-load-the-corpus"><span class="header-section-number">3.2</span> Step 1: Load the Corpus</h2>
<p>Navigate to <strong>Manage Corpus Data</strong>. Under the <strong>Internal</strong> tab, select the <strong>Large Dictionary</strong> model, then choose <strong>H_HAPE_mini</strong> from the corpus dropdown. Click <strong>Process Target</strong>.</p>
<p>After loading, the corpus summary will confirm:</p>
<pre><code>Number of part-of-speech tokens in corpus:  1,390,260
Number of DocuScope tokens in corpus:        1,078,344
Number of documents in corpus:               2,700</code></pre>
<section id="process-document-metadata" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="process-document-metadata"><span class="header-section-number">3.2.1</span> Process Document Metadata</h3>
<p>When prompted about document categories, select <strong>Yes</strong> and click <strong>Process Document Metadata</strong>. The H_HAPE_mini filenames encode author group and text type (e.g., <code>gpt4_acad_0744</code>, <code>human_spok_1393</code>, <code>llama_tvm_0020</code>). DocuScope CA extracts the author group prefix as the document category.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What counts as metadata here?
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this workflow, <strong>metadata</strong> means document-level labels extracted from the filenames, not additional linguistic annotation. For <code>H_HAPE_mini</code>, the filename prefix identifies the author group (<code>gpt4</code>, <code>human</code>, or <code>llama</code>), while later parts of the ID preserve the text type.</p>
<p>Processing metadata makes those author-group labels available throughout the app. That is what allows you to compare categories in later workflows, while still using the document IDs in KWIC to inspect text type at the same time.</p>
</div>
</div>
<p>The metadata will identify three categories:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Category</th>
<th>Description</th>
<th>Documents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>gpt4</code></td>
<td>Texts authored by ChatGPT-4o</td>
<td>900</td>
</tr>
<tr class="even">
<td><code>human</code></td>
<td>Texts authored by human writers</td>
<td>900</td>
</tr>
<tr class="odd">
<td><code>llama</code></td>
<td>Texts authored by Llama 8B Instruct</td>
<td>900</td>
</tr>
</tbody>
</table>
<p>Each category spans all six text types in the corpus: academic articles, news, fiction, spoken language, blog posts, and TV/movie scripts. Because the corpus is balanced across both author groups and text types, differences across categories are more plausibly attributed to authorship style than to topic selection alone.</p>
<hr>
</section>
</section>
<section id="step-2-identify-a-target-word-with-token-frequencies" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="step-2-identify-a-target-word-with-token-frequencies"><span class="header-section-number">3.3</span> Step 2: Identify a Target Word with Token Frequencies</h2>
<p>Before computing collocations, it helps to identify a candidate word with sufficient corpus frequency. Navigate to <strong>Token Frequencies</strong> and click <strong>Frequency Table</strong> in the sidebar.</p>
<p>The table shows frequency, relative frequency, and range for every lemma in the corpus. Sort by <strong>Freq</strong> (absolute frequency) descending to see the most common tokens. To locate a specific word, use the <strong>Search</strong> button in the table toolbar and enter <code>important</code>.</p>
<p>The search will return the relevant row for the adjective:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Token</th>
<th>Tag</th>
<th>AF</th>
<th>RF (per million)</th>
<th>Range (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>important</td>
<td>JJ</td>
<td>381</td>
<td>274</td>
<td>69.78</td>
</tr>
</tbody>
</table>
<p>With 381 occurrences distributed across 69.78% of documents, <em>important</em> is frequent and wide-ranging enough to support a meaningful collocation analysis. Its semantic load — it signals evaluation, emphasis, and epistemic stance — makes it a theoretically motivated target for examining how human and AI writers construct argumentative language.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Choosing a node word for collocation analysis:</strong> A good node word should have sufficient corpus frequency (at least 50–100 occurrences is recommended) and a clear semantic or functional role. Very high-frequency function words like <em>the</em> or <em>is</em> tend to produce collocation tables dominated by other function words. Evaluative adjectives like <em>important</em>, <em>significant</em>, or <em>critical</em> are productive targets because their collocational profile reveals how writers construct stance and emphasis.</p>
<p>In this workflow, <em>important</em> is a useful choice because it is frequent enough to analyze reliably, interpretable across multiple genres, and likely to reveal evaluative framing rather than just topic-specific vocabulary.</p>
</div>
</div>
<hr>
</section>
<section id="step-3-compute-collocations" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="step-3-compute-collocations"><span class="header-section-number">3.4</span> Step 3: Compute Collocations</h2>
<p>Navigate to <strong>Collocations</strong>. The <strong>Collocation Configuration</strong> panel will appear. Enter <code>important</code> in the <strong>Node word</strong> field and press Enter.</p>
<p>Use the following settings:</p>
<ul>
<li><strong>Span:</strong> 4 Left, 4 Right (the default — considers up to four tokens on each side of the node)</li>
<li><strong>Association measure:</strong> NPMI (Normalized Pointwise Mutual Information — the default)</li>
<li><strong>Anchor tag:</strong> No Tag (search by lemma, not restricted to a specific POS)</li>
</ul>
<p>Click <strong>Collocations Table</strong> in the sidebar.</p>
<p>This workflow moves from <strong>Token Frequencies</strong> to <strong>Collocations</strong> for a reason: the frequency table helps you choose a viable node word, while the collocations table shows which words are statistically associated with that node.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why start with NPMI?
</div>
</div>
<div class="callout-body-container callout-body">
<p>PMI is one of the most widely used association measures, but it is highly sensitive to rare combinations. In practice, that often means researchers need to add an extra frequency filter or manually ignore very low-frequency collocates.</p>
<p>NPMI is often a good exploratory default because it rescales scores to a bounded range and usually produces a more interpretable ranking for mid-sized corpora. It does not eliminate rare-item effects, but it can reduce how much manual filtering is needed.</p>
<p>The key methodological question is not which measure is universally best, but which one produces a ranking that is useful for your corpus size and research goal.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Why use No Tag first?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Start with <strong>No Tag</strong> when the node word is already clear enough for exploratory analysis. Add an anchor tag only when you need to disambiguate a word that can play multiple important grammatical roles, or when you want tighter control over what counts as a match.</p>
</div>
</div>
<section id="understanding-npmi" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="understanding-npmi"><span class="header-section-number">3.4.1</span> Understanding NPMI</h3>
<p>NPMI is a normalized variant of Pointwise Mutual Information. For a pair of words (<span class="math inline">\(w_1\)</span>, <span class="math inline">\(w_2\)</span>), PMI is defined as:</p>
<p><span class="math display">\[\text{PMI}(w_1, w_2) = \log_2 \frac{P(w_1, w_2)}{P(w_1) \cdot P(w_2)}\]</span></p>
<p>where <span class="math inline">\(P(w_1, w_2)\)</span> is the probability of the pair co-occurring within the span window and <span class="math inline">\(P(w_1)\)</span>, <span class="math inline">\(P(w_2)\)</span> are their individual corpus probabilities. NPMI divides PMI by <span class="math inline">\(-\log_2 P(w_1, w_2)\)</span>, rescaling scores to the range <span class="math inline">\([-1, 1]\)</span>:</p>
<ul>
<li><strong>NPMI near 1.0:</strong> the words co-occur almost exclusively with each other</li>
<li><strong>NPMI near 0:</strong> co-occurrence is no greater than chance</li>
<li><strong>NPMI near -1.0:</strong> the words actively avoid each other</li>
</ul>
<p>High NPMI identifies <em>distinctive</em> collocates — words whose presence near the node word is statistically surprising given their overall corpus frequency. This is different from raw frequency: a very common word like <em>the</em> will rarely achieve high NPMI even if it appears near <em>important</em> hundreds of times.</p>
<p>Whether rare-item inflation matters depends on the research question. If you want stable, recurring phraseology, the very top of the table may contain too much noise from one-off combinations. If you are using collocations as a discovery tool for close reading, those unusual pairings may still be worth inspecting.</p>
</section>
<section id="reading-the-collocations-table" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="reading-the-collocations-table"><span class="header-section-number">3.4.2</span> Reading the Collocations Table</h3>
<p>The table returns five columns:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Column</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Token</strong></td>
<td>The collocate word</td>
</tr>
<tr class="even">
<td><strong>Tag</strong></td>
<td>Its CLAWS7 part-of-speech tag</td>
</tr>
<tr class="odd">
<td><strong>Freq Span</strong></td>
<td>How many times it appears within the span of <em>important</em></td>
</tr>
<tr class="even">
<td><strong>MI</strong></td>
<td>The NPMI score</td>
</tr>
<tr class="odd">
<td><strong>Freq Total</strong></td>
<td>How many times it appears anywhere in the corpus</td>
</tr>
</tbody>
</table>
<p>The table is sorted by NPMI descending. The top rows are typically <strong>hapax legomena</strong> — words that appear only once in the corpus and that single occurrence happens to be near the node word. These achieve high NPMI because <span class="math inline">\(P(w_1, w_2)\)</span> is as high as it can be relative to <span class="math inline">\(P(w_2)\)</span>, but they contribute little to an account of typical usage patterns.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../images/vignettes/collocations-important-table.png" class="img-fluid figure-img" alt="Collocations table showing Token, Tag, Freq Span, Freq Total, and MI columns for the node word 'important'. Top rows include hapax legomena like 'acronym' (NN1, Freq Span=2, Freq Total=1, MI=0.661) and 'advertiser', 'caveats', 'differ' (Freq Span=1, Freq Total=1, MI=0.580)."></p>
<figcaption>Collocations table for <em>important</em> (NPMI, 4L–4R span). Top results are maximally associated but rare; scrolling or tag-filtering reveals higher-frequency collocates.</figcaption>
</figure>
</div>
<p>To investigate higher-frequency collocates, use the <strong>Select tags to filter</strong> accordion. Clicking individual POS tags limits the display to collocates of that grammatical class, making it easier to identify meaningful patterns against the noise of rare items. Alternatively, scroll the table toward the end (lower NPMI scores) to find the most frequent collocates.</p>
<p>Selected collocates of interest, retrieved by scrolling or tag-filtering:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Token</th>
<th>Tag</th>
<th>Freq Span</th>
<th>Freq Total</th>
<th>NPMI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>note</td>
<td>VVI</td>
<td>4</td>
<td>11</td>
<td>0.564</td>
</tr>
<tr class="even">
<td>parameter</td>
<td>NN1</td>
<td>5</td>
<td>18</td>
<td>0.552</td>
</tr>
<tr class="odd">
<td>thing</td>
<td>NN1</td>
<td>3</td>
<td>264</td>
<td>0.488</td>
</tr>
<tr class="even">
<td>role</td>
<td>NN1</td>
<td>9</td>
<td>455</td>
<td>0.358</td>
</tr>
<tr class="odd">
<td>very</td>
<td>RG</td>
<td>13</td>
<td>742</td>
<td>0.359</td>
</tr>
<tr class="even">
<td>also</td>
<td>RR</td>
<td>24</td>
<td>1,750</td>
<td>0.357</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tag glossary:</strong> VVI = infinitive form of a main verb; NN1 = singular common noun; RG = degree adverb (e.g., <em>very</em>, <em>quite</em>); RR = general adverb (e.g., <em>also</em>, <em>really</em>).</p>
</div>
</div>
<p>Three patterns emerge from this selection:</p>
<ol type="1">
<li><p><strong>“important to note”</strong> (note VVI, NPMI=0.564): The infinitive <em>note</em> appears only 11 times in the entire corpus, yet 4 of those occurrences fall within the span of <em>important</em>. This is a strong statistical signal for the fixed phrase <em>it is important to note</em> — a formulaic hedging device common in academic and instructional writing.</p></li>
<li><p><strong>“important role/component/element”</strong> (role NN1, NPMI=0.358): The noun <em>role</em> appears frequently across the corpus (455 times) but still achieves a moderate NPMI score, reflecting the conventional pre-nominal pattern <em>an important role in…</em>, <em>an important component of…</em>. These nominal collocates signal that writers use <em>important</em> to preface substantive claims about the function of entities in a system.</p></li>
<li><p><strong>Intensifiers</strong> (<em>very</em> RG, <em>also</em> RR): These high-frequency adverbs achieve similar NPMI scores but serve different functions. <em>Very</em> appears in emphatic constructions (<em>very important consideration</em>), while <em>also</em> most often participates in additive structures (<em>also important is…</em> or <em>it is also important to…</em>).</p></li>
</ol>
<hr>
</section>
</section>
<section id="step-4-examine-concordance-lines-with-kwic" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="step-4-examine-concordance-lines-with-kwic"><span class="header-section-number">3.5</span> Step 4: Examine Concordance Lines with KWIC</h2>
<p>The collocations table reveals <em>which</em> words associate with <em>important</em>, but not <em>how</em> those associations are deployed in actual sentences. Navigate to <strong>Key Words in Context (KWIC)</strong> to investigate the concordance lines.</p>
<p>In the <strong>KWIC Configuration</strong> panel, enter <code>important</code> in the <strong>Node word</strong> field. Leave <strong>Search mode</strong> set to <strong>Fixed</strong> (exact match) and click <strong>KWIC Table</strong> in the sidebar.</p>
<p>Using <strong>Fixed</strong> search is appropriate here because the goal is to examine the exact lexical item <em>important</em>, not related forms such as <em>importance</em> or <em>importantly</em>.</p>
<p>The table returns one row per corpus occurrence of <em>important</em>, with four columns: <strong>Doc ID</strong>, <strong>Pre-Node</strong> (left context), <strong>Node</strong>, and <strong>Post-Node</strong> (right context). The Doc ID encodes both the author group and the text type (e.g., <code>gpt4_acad_0744</code> = GPT-4, academic text #744).</p>
<p>Because the table is sorted by document ID, rows with shared prefixes cluster together. That makes it possible to scan stretches like <code>gpt4_acad_*</code>, <code>human_acad_*</code>, or <code>llama_tvm_*</code> as rough groupings before doing any additional filtering.</p>
<p>The examples below are illustrative slices of the concordance, not exhaustive summaries of every occurrence in the corpus.</p>
<section id="patterns-in-gpt-4-academic-writing" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="patterns-in-gpt-4-academic-writing"><span class="header-section-number">3.5.1</span> Patterns in GPT-4 Academic Writing</h3>
<p>The first rows in the table (sorted alphabetically, so <code>gpt4_acad_*</code> documents appear first) reveal a striking pattern:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 28%">
<col style="width: 17%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Doc ID</th>
<th>Pre-Node</th>
<th>Node</th>
<th>Post-Node</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>gpt4_acad_0178</td>
<td>and Fink, 2011). Equally</td>
<td><strong>important</strong></td>
<td>is the potential utility of machine learning</td>
</tr>
<tr class="even">
<td>gpt4_acad_0382</td>
<td>the achievements in vehicle platooning signify</td>
<td><strong>important</strong></td>
<td>strides toward that vision. Engineers and</td>
</tr>
<tr class="odd">
<td>gpt4_acad_0428</td>
<td>adoption. The social dimension is equally</td>
<td><strong>important</strong></td>
<td>, requiring a shift in public perception</td>
</tr>
<tr class="even">
<td>gpt4_acad_0641</td>
<td>harm reduction strategies and EC regulation,</td>
<td><strong>important</strong></td>
<td>steps toward reducing the considerable public health</td>
</tr>
<tr class="odd">
<td>gpt4_acad_0744</td>
<td>2012). However, it is</td>
<td><strong>important</strong></td>
<td>to recognize the need for continued calibration</td>
</tr>
<tr class="even">
<td>gpt4_acad_0797</td>
<td>al., 2017). Equally</td>
<td><strong>important</strong></td>
<td>are economic considerations. The economic viability</td>
</tr>
<tr class="odd">
<td>gpt4_acad_0969</td>
<td>conservation practices has gained recognition as an</td>
<td><strong>important</strong></td>
<td>element for achieving sustainable resource management</td>
</tr>
<tr class="even">
<td>gpt4_acad_1034</td>
<td>, or even brain enhancement technologies raises</td>
<td><strong>important</strong></td>
<td>questions regarding equity, access, and</td>
</tr>
<tr class="odd">
<td>gpt4_acad_1089</td>
<td>for instance, is gradually becoming an</td>
<td><strong>important</strong></td>
<td>component in prion research, allowing visualization</td>
</tr>
</tbody>
</table>
<p>Two constructions dominate:</p>
<ul>
<li><strong>“Equally important is/are…”</strong> — this discourse connector appears twice in just these nine rows (<code>gpt4_acad_0178</code>, <code>gpt4_acad_0797</code>). It functions as a cohesive device for introducing a new argument of equal weight to the preceding one. The inverted copular structure (<em>Equally important are economic considerations</em>) is a hallmark of formal written prose.</li>
<li><strong>“it is important to [VERB]”</strong> — here, <em>to recognize</em> (<code>gpt4_acad_0744</code>). This epistemic hedge is the grammatical environment predicted by the NPMI collocate <em>note</em> (VVI): the infinitive follows <em>important</em> in a <em>to</em>-infinitive complement.</li>
</ul>
</section>
<section id="patterns-in-human-academic-writing" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="patterns-in-human-academic-writing"><span class="header-section-number">3.5.2</span> Patterns in Human Academic Writing</h3>
<p>Scrolling to the <code>human_acad_*</code> rows reveals a different profile:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 28%">
<col style="width: 17%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Doc ID</th>
<th>Pre-Node</th>
<th>Node</th>
<th>Post-Node</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>human_acad_0557</td>
<td>of proportional population growth rates has some</td>
<td><strong>important</strong></td>
<td>consequences. For example, two ecosystems</td>
</tr>
<tr class="even">
<td>human_acad_0578</td>
<td>’s empowerment in the agricultural sector is</td>
<td><strong>important</strong></td>
<td>, given that agriculture remains the basis</td>
</tr>
<tr class="odd">
<td>human_acad_0611</td>
<td>bean level is not available. Another</td>
<td><strong>important</strong></td>
<td>parameter related to cocoa bean quality is</td>
</tr>
<tr class="even">
<td>human_acad_0632</td>
<td>of biomass and coal differ in many</td>
<td><strong>important</strong></td>
<td>ways, which can result in completely</td>
</tr>
<tr class="odd">
<td>human_acad_0641</td>
<td>a smoker has been identified as an</td>
<td><strong>important</strong></td>
<td>barrier to smoking cessation</td>
</tr>
<tr class="even">
<td>human_acad_0641</td>
<td>al., 2009). Another</td>
<td><strong>important</strong></td>
<td>factor in the transition from smoker to</td>
</tr>
<tr class="odd">
<td>human_acad_0641</td>
<td>, 2013), it is therefore</td>
<td><strong>important</strong></td>
<td>that such symptoms are minimised to ensure</td>
</tr>
<tr class="even">
<td>human_acad_0680</td>
<td>The improvement compared to AC is certainly</td>
<td><strong>important</strong></td>
<td>, but still, there are obvious</td>
</tr>
<tr class="odd">
<td>human_acad_0741</td>
<td>of structure on lipolysis is therefore an</td>
<td><strong>important</strong></td>
<td>aspect to consider when designing oleogel systems</td>
</tr>
</tbody>
</table>
<p>Human academic writing uses <em>important</em> primarily in two ways:</p>
<ul>
<li><strong>Pre-nominal use with empirical nouns</strong>: “Another important <em>parameter</em>”, “an important <em>barrier</em>”, “an important <em>factor</em>”, “an important <em>aspect</em>” — each modified noun names a specific research-domain concept (parameter, barrier, factor, aspect), grounding the claim in technical vocabulary.</li>
<li><strong>Complement clause construction</strong>: “it is therefore important <em>that</em> such symptoms are minimised” — notably, this is a <em>that</em>-complement clause rather than the infinitive <em>to</em>-complement (<em>it is important to</em>) common in GPT-4 texts.</li>
</ul>
<p>The “Equally important is/are…” discourse connector, conspicuous in the GPT-4 rows, does not appear in the visible human academic rows.</p>
</section>
<section id="patterns-in-llama-tvmovie-script-writing" class="level3" data-number="3.5.3">
<h3 data-number="3.5.3" class="anchored" data-anchor-id="patterns-in-llama-tvmovie-script-writing"><span class="header-section-number">3.5.3</span> Patterns in Llama TV/Movie Script Writing</h3>
<p>Scrolling toward the <code>llama_tvm_*</code> rows (alphabetically later) shows a markedly different register:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 28%">
<col style="width: 17%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Doc ID</th>
<th>Pre-Node</th>
<th>Node</th>
<th>Post-Node</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>llama_tvm_0020</td>
<td>We need to focus on what’s</td>
<td><strong>important</strong></td>
<td>. Connor looks up at him,</td>
</tr>
<tr class="even">
<td>llama_tvm_0020</td>
<td>hope in his eyes. What’s</td>
<td><strong>important</strong></td>
<td>, Dad? Dennis takes another drag</td>
</tr>
<tr class="odd">
<td>llama_tvm_0020</td>
<td>You need to focus on what’s</td>
<td><strong>important</strong></td>
<td>. Dennis nods, determination etched on</td>
</tr>
<tr class="even">
<td>llama_tvm_0113</td>
<td>of seniors walking by, looking very</td>
<td><strong>important</strong></td>
<td>and very… senior. Fred’s</td>
</tr>
<tr class="odd">
<td>llama_tvm_0779</td>
<td>. Let’s get back to the</td>
<td><strong>important</strong></td>
<td>stuff. Like the report. Yeah</td>
</tr>
<tr class="even">
<td>llama_tvm_0820</td>
<td>be gross, it’s actually really</td>
<td><strong>important</strong></td>
<td>for us to study owl pellets</td>
</tr>
</tbody>
</table>
<p>Here, <em>important</em> functions as an <strong>evaluative predicate in dialogue</strong> — “What’s important?” / “focus on what’s important” / “the important stuff”. The informal repetition, sentence fragments, and character voice typical of scripts contrast sharply with both the GPT-4 academic and human academic patterns. This illustrates a crucial methodological point: genre can constrain vocabulary use as powerfully as authorship does.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Because document IDs in H_HAPE_mini encode both author group and text type (e.g., <code>gpt4_acad_0744</code> encodes author=gpt4, type=academic), the KWIC table allows researchers to trace patterns across both dimensions simultaneously without needing additional metadata filtering. A researcher can scan all <code>*_acad_*</code> rows to compare academic writing across authors, or scan all <code>gpt4_*</code> rows to compare GPT-4 writing across genres.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="interpretation" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="interpretation"><span class="header-section-number">3.6</span> Interpretation</h2>
<p>The workflow — Token Frequencies → Collocations → KWIC — traces a path from corpus-level statistics to individual text evidence. Each step contributes something the others cannot:</p>
<ol type="1">
<li><p><strong>Token Frequencies</strong> established that <em>important</em> is sufficiently frequent and widely distributed to support analysis (AF=381, Range=69.78%). Without this step, we might not know whether any collocational patterns found reflect genuine tendencies or are artefacts of a handful of documents.</p></li>
<li><p><strong>Collocations (NPMI)</strong> revealed the strongest statistical associates: <em>note</em> (VVI) with NPMI=0.564 signals the phrase <em>important to note</em>, while <em>role</em> and <em>parameter</em> (both NN1) signal nominal collocates of varying frequency. The NPMI score reweights co-occurrence by corpus frequency, preventing common words from dominating the results.</p></li>
<li><p><strong>KWIC</strong> gave us evidence for the patterns latent in the statistics. The strong NPMI of <em>note</em> (VVI) reflects the GPT-4 academic phrase “it is important to <em>recognize</em>”, while the high frequency of <em>role</em> as collocate appears across both human and AI academic texts. Most strikingly, the “Equally important is/are…” construction — a cohesive discourse connector for introducing parallel arguments — appears repeatedly in GPT-4 academic texts but is absent from the visible human academic concordance lines.</p></li>
</ol>
<p>These findings align with prior observations about AI-generated academic writing: LLMs tend to favor <strong>formulaic discourse organization devices</strong> (such as “Equally important”, “It is important to note”) that signal academic register without necessarily being specific to the topic at hand. Human academic writing, by contrast, tends to attach <em>important</em> to content-specific technical vocabulary (parameter, barrier, consequences) reflecting engagement with the disciplinary literature.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The patterns observed here are suggestive rather than definitive. A full statistical comparison across author groups — including keyness testing and effect-size measures — would require the <strong>Compare Corpus Parts</strong> workflow (see the <a href="../vignettes/workflow-passive-constructions.html">passive constructions vignette</a> for an example). The KWIC and Collocations tools are best used for targeted qualitative investigation of candidate patterns identified by quantitative means.</p>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-reinhart2025llms" class="csl-entry" role="listitem">
Reinhart, Alex, Ben Markey, Michael Laudenbach, et al. 2025. <span>“Do LLMs Write Like Humans? Variation in Grammatical and Rhetorical Styles.”</span> <em>Proceedings of the National Academy of Sciences</em> 122 (8): e2422455122. <a href="https://doi.org/10.1073/pnas.2422455122">https://doi.org/10.1073/pnas.2422455122</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../vignettes/workflow-passive-constructions.html" class="pagination-link" aria-label="Passive Constructions Across Disciplines">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Passive Constructions Across Disciplines</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../vignettes/external-corpus.html" class="pagination-link" aria-label="Creating and Using an External Corpus File">
        <span class="nav-page-text">Creating and Using an External Corpus File</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>