# Elsevier {.unnumbered}

{{< iconify material-symbols:construction >}} Under construction.

For convenience, DocuScope CAC come with some pre-processed data. One of those was compiled specifically for the tool. It contains published academic articles, which were harvested from Elesevier open access. The entire dataset includes more than 40,000 articles. The data processed and saved for the tool have 20 randomly sampled articles from 20 disciplines.

### Corpus Metadata

|doc_id           |doi                               |pub_year|subj_short|subj_name                                   |title                                                                                                                                                                                                                           |
|-----------------|----------------------------------|--------|---------|--------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|S0039368115001612|10.1016/j.shpsa.2015.11.001       |2016    |ARTS     |Arts and Humanities                         |Experiment and speculation in seventeenth-century Italy: The case of Geminiano Montanari                                                                                                                                        |
|S0160932718300012|10.1016/j.endeavour.2018.01.001   |2018    |ARTS     |Arts and Humanities                         |Why the history of public consultation matters for contemporary health policy                                                                                                                                                   |
|S0039368116300449|10.1016/j.shpsa.2016.08.003       |2016    |ARTS     |Arts and Humanities                         |Repertoires: A post-Kuhnian perspective on scientific change and collaborative research                                                                                                                                         |
|S1369848614000867|10.1016/j.shpsc.2014.07.006       |2014    |ARTS     |Arts and Humanities                         |Testimonies of precognition and encounters with psychiatry in letters to J. B. Priestley                                                                                                                                        |
|S1369848617301814|10.1016/j.shpsc.2019.01.002       |2019    |ARTS     |Arts and Humanities                         |Between mice and sheep: Biotechnology, agricultural science and animal models in late-twentieth century Edinburgh                                                                                                               |
|S1369848613001507|10.1016/j.shpsc.2013.11.001       |2014    |ARTS     |Arts and Humanities                         |A weakened mechanism is still a mechanism: On the causal role of absences in mechanistic explanation                                                                                                                            |
|S0039368118300190|10.1016/j.shpsa.2018.11.006       |2019    |ARTS     |Arts and Humanities                         |Mavericks and lotteries                                                                                                                                                                                                         |
|S0160932715300235|10.1016/j.endeavour.2015.10.005   |2016    |ARTS     |Arts and Humanities                         |The victims of unethical human experiments and coerced research under National Socialism                                                                                                                                        |
|S0160932715300284|10.1016/j.endeavour.2016.03.005   |2016    |ARTS     |Arts and Humanities                         |Toxic confusion: The dilemma of antibiotic regulation in West German food production (1951-1990)                                                                                                                                |
|S0160932716300308|10.1016/j.endeavour.2016.07.002   |2016    |ARTS     |Arts and Humanities                         |CO2, the greenhouse effect and global warming: from the pioneering work of Arrhenius and Callendar to today's Earth System Models                                                                                               |
|S1369848613001696|10.1016/j.shpsc.2013.11.007       |2014    |ARTS     |Arts and Humanities                         |Wartime women giving birth: Narratives of pregnancy and childbirth, Britain c. 1939-1960                                                                                                                                        |
|S0039368117300390|10.1016/j.shpsa.2017.10.005       |2018    |ARTS     |Arts and Humanities                         |Realism on the rocks: Novel success and James Hutton's theory of the earth                                                                                                                                                      |
|S136984861630067X|10.1016/j.shpsc.2016.09.003       |2016    |ARTS     |Arts and Humanities                         |Diagnosis and causal explanation in psychiatry                                                                                                                                                                                  |
|S1369848613001349|10.1016/j.shpsc.2013.10.009       |2014    |ARTS     |Arts and Humanities                         |Making birth defects 'preventable': Pre-conceptional vitamin supplements and the politics of risk reduction                                                                                                                     |
|S0039368117300717|10.1016/j.shpsa.2017.03.004       |2017    |ARTS     |Arts and Humanities                         |Narrative constructs in modern clinical case reporting                                                                                                                                                                          |
|S1369848615001284|10.1016/j.shpsc.2015.09.002       |2016    |ARTS     |Arts and Humanities                         |Saving the gene pool for the future: Seed banks as archives                                                                                                                                                                     |
|S1369848615001132|10.1016/j.shpsc.2015.08.005       |2016    |ARTS     |Arts and Humanities                         |Documenting genomics: Applying archival theory to preserving the records of the Human Genome Project                                                                                                                            |
|S0160932716300035|10.1016/j.endeavour.2016.01.001   |2016    |ARTS     |Arts and Humanities                         |Museum perceptions and productions: American migrations of a Maori hei-tiki                                                                                                                                                     |
|S136984861400048X|10.1016/j.shpsc.2014.05.008       |2014    |ARTS     |Arts and Humanities                         |Blood groups and human groups: Collecting and calibrating genetic data after World War Two                                                                                                                                      |
|S1369848613001763|10.1016/j.shpsc.2013.12.002       |2014    |ARTS     |Arts and Humanities                         |The demand for pregnancy testing: The aschheim-zondek reaction, diagnostic versatility, and laboratory services in 1930s britain                                                                                                |
|S1934590915002234|10.1016/j.stem.2015.05.014        |2015    |BIOC     |Biochemistry, Genetics and Molecular Biology|Transcriptional Mechanisms of Proneural Factors and REST in Regulating Neuronal Reprogramming of Astrocytes                                                                                                                     |
|S2212877818304861|10.1016/j.molmet.2018.07.003      |2018    |BIOC     |Biochemistry, Genetics and Molecular Biology|Individual islet respirometry reveals functional diversity within the islet population of mice and human donors                                                                                                                 |
|S1097276516304166|10.1016/j.molcel.2016.08.002      |2016    |BIOC     |Biochemistry, Genetics and Molecular Biology|53BP1 Integrates DNA Repair and p53-Dependent Cell Fate Decisions via Distinct Mechanisms                                                                                                                                       |
|S2352396417302906|10.1016/j.ebiom.2017.07.017       |2017    |BIOC     |Biochemistry, Genetics and Molecular Biology|Impaired Barrier Function and Autoantibody Generation in Malnutrition Enteropathy in Zambia                                                                                                                                     |
|S0378111913016995|10.1016/j.gene.2013.12.038        |2014    |BIOC     |Biochemistry, Genetics and Molecular Biology|Analysis of changes in transcription start site distribution by a classification approach                                                                                                                                       |
|S0006349515006736|10.1016/j.bpj.2015.06.061         |2015    |BIOC     |Biochemistry, Genetics and Molecular Biology|Structure, Dynamics, and Allosteric Potential of Ionotropic Glutamate Receptor N-Terminal Domains                                                                                                                               |
|S0167488918302519|10.1016/j.bbamcr.2018.08.005      |2018    |BIOC     |Biochemistry, Genetics and Molecular Biology|Establishing life is a calcium-dependent TRiP: Transient receptor potential channels in reproduction                                                                                                                            |
|S089865681400312X|10.1016/j.cellsig.2014.09.008     |2015    |BIOC     |Biochemistry, Genetics and Molecular Biology|Mechanism of enzymatic reaction and protein-protein interactions of PLD from a 3D structural model                                                                                                                              |
|S2212877815000770|10.1016/j.molmet.2015.04.005      |2015    |BIOC     |Biochemistry, Genetics and Molecular Biology|Peroxisome proliferator-activated receptor alpha plays a crucial role in behavioral repetition and cognitive flexibility in mice                                                                                                |
|S0945053X1730094X|10.1016/j.matbio.2017.06.002      |2018    |BIOC     |Biochemistry, Genetics and Molecular Biology|Tissue alignment enhances remodeling potential of tendon-derived cells - Lessons from a novel microtissue model of tendon scarring                                                                                              |
|S0168952514000559|10.1016/j.tig.2014.04.001         |2014    |BIOC     |Biochemistry, Genetics and Molecular Biology|Nervous decision-making: To divide or differentiate                                                                                                                                                                             |
|S009286741930457X|10.1016/j.cell.2019.04.038        |2019    |BIOC     |Biochemistry, Genetics and Molecular Biology|SCAF4 and SCAF8, mRNA Anti-Terminator Proteins                                                                                                                                                                                  |
|S2211124715012462|10.1016/j.celrep.2015.10.057      |2015    |BIOC     |Biochemistry, Genetics and Molecular Biology|Evolving Models of Pavlovian Conditioning: Cerebellar Cortical Dynamics in Awake Behaving Mice                                                                                                                                  |
|S0012160615002109|10.1016/j.ydbio.2015.04.010       |2015    |BIOC     |Biochemistry, Genetics and Molecular Biology|Imprinted expression in cystic embryoid bodies shows an embryonic and not an extra-embryonic pattern                                                                                                                            |
|S2213671118300341|10.1016/j.stemcr.2018.01.008      |2018    |BIOC     |Biochemistry, Genetics and Molecular Biology|Generation of Functioning Nephrons by Implanting Human Pluripotent Stem Cell-Derived Kidney Progenitors                                                                                                                         |
|S2352396414000024|10.1016/j.ebiom.2014.09.001       |2014    |BIOC     |Biochemistry, Genetics and Molecular Biology|In vivo application of tissue-engineered veins using autologous peripheral whole blood: A proof of concept study                                                                                                                |
|S2352396415000997|10.1016/j.ebiom.2015.04.005       |2015    |BIOC     |Biochemistry, Genetics and Molecular Biology|Liposomal Nanoparticles of a Spleen Tyrosine Kinase P-Site Inhibitor Amplify the Potency of Low Dose Total Body Irradiation Against Aggressive B-Precursor Leukemia and Yield Superior Survival Outcomes in Mice                |
|S0079610715000139|10.1016/j.pbiomolbio.2015.02.003  |2015    |BIOC     |Biochemistry, Genetics and Molecular Biology|Phosphopeptide interactions with BRCA1 BRCT domains: More than just a motif                                                                                                                                                     |
|S0047637415000068|10.1016/j.mad.2015.01.004         |2015    |BIOC     |Biochemistry, Genetics and Molecular Biology|Serum copper to zinc ratio: Relationship with aging and health status                                                                                                                                                           |
|S2212877819301309|10.1016/j.molmet.2019.03.004      |2019    |BIOC     |Biochemistry, Genetics and Molecular Biology|Laser capture microdissection of human pancreatic islets reveals novel eQTLs associated with type 2 diabetes                                                                                                                    |
|S0148296316302879|10.1016/j.jbusres.2016.05.002     |2016    |BUSI     |Business, Management and Accounting         |Localization in China: How guanxi moderates Sino–US business relationships                                                                                                                                                      |
|S0169207014001307|10.1016/j.ijforecast.2014.06.006  |2015    |BUSI     |Business, Management and Accounting         |Macroeconomic information, structural change, and the prediction of fiscal aggregates                                                                                                                                           |
|S0148296318305319|10.1016/j.jbusres.2018.10.050     |2019    |BUSI     |Business, Management and Accounting         |The impact of virtual, augmented and mixed reality technologies on the customer experience                                                                                                                                      |
|S0148296315003926|10.1016/j.jbusres.2015.09.004     |2016    |BUSI     |Business, Management and Accounting         |Increasing sample size compensates for data problems in segmentation studies                                                                                                                                                    |
|S2352673417300835|10.1016/j.jbvi.2017.12.001        |2018    |BUSI     |Business, Management and Accounting         |I am what I am - How nascent entrepreneurs’ social identity affects their entrepreneurial self-efficacy                                                                                                                         |
|S0890838917300136|10.1016/j.bar.2017.02.002         |2018    |BUSI     |Business, Management and Accounting         |Voluntary disclosure, greenhouse gas emissions and business performance: Assessing the first decade of reporting                                                                                                                |
|S0167811619300473|10.1016/j.ijresmar.2019.07.007    |2020    |BUSI     |Business, Management and Accounting         |On the monetization of mobile apps                                                                                                                                                                                              |
|S2213078019300234|10.1016/j.jort.2019.04.001        |2019    |BUSI     |Business, Management and Accounting         |Dimensions in the nature-based tourism experiencescape: An explorative analysis                                                                                                                                                 |
|S0148296315003240|10.1016/j.jbusres.2015.07.033     |2016    |BUSI     |Business, Management and Accounting         |Exploring reflective learning during the extended consumption of life experiences                                                                                                                                               |
|S096969891830167X|10.1016/j.jretconser.2018.11.006  |2019    |BUSI     |Business, Management and Accounting         |Clicking the boredom away – Exploring impulse fashion buying behavior online                                                                                                                                                    |
|S0148296319302188|10.1016/j.jbusres.2019.03.035     |2019    |BUSI     |Business, Management and Accounting         |How entrepreneurial SMEs compete through digital platforms: The roles of digital platform capability, network capability and ambidexterity                                                                                      |
|S2211973619300637|10.1016/j.tmp.2019.05.009         |2019    |BUSI     |Business, Management and Accounting         |Sources of distrust: Airbnb guests' perspectives                                                                                                                                                                                |
|S0148296316303058|10.1016/j.jbusres.2016.05.006     |2016    |BUSI     |Business, Management and Accounting         |When do franchisors select entrepreneurial franchisees? An organizational identity perspective                                                                                                                                  |
|S2211973619300558|10.1016/j.tmp.2019.05.001         |2019    |BUSI     |Business, Management and Accounting         |The tourism partnership life cycle in Estonia: Striving towards sustainable multisectoral rural tourism collaboration                                                                                                           |
|S0148296319302024|10.1016/j.jbusres.2019.03.030     |2019    |BUSI     |Business, Management and Accounting         |Is my company really doing good? Factors influencing employees' evaluation of the authenticity of their company's corporate social responsibility engagement                                                                    |
|S0019850116303431|10.1016/j.indmarman.2016.12.005   |2017    |BUSI     |Business, Management and Accounting         |Using gamification to transform the adoption of servitization                                                                                                                                                                   |
|S0263786317304064|10.1016/j.ijproman.2018.01.004    |2018    |BUSI     |Business, Management and Accounting         |Project capabilities for operational outcomes in inter-organisational settings: The case of London Heathrow Terminal 2                                                                                                          |
|S0148296318304788|10.1016/j.jbusres.2018.10.005     |2020    |BUSI     |Business, Management and Accounting         |Effective entrepreneurial marketing on Facebook – A longitudinal study                                                                                                                                                          |
|S0278431916300044|10.1016/j.ijhm.2016.01.011        |2016    |BUSI     |Business, Management and Accounting         |The effect of visual and auditory elements on patrons' liquor-ordering behavior: An empirical study                                                                                                                             |
|S0148296317303752|10.1016/j.jbusres.2017.10.003     |2018    |BUSI     |Business, Management and Accounting         |PROMISING THE DREAM: Changing destination image of London through the effect of website place                                                                                                                                   |
|S0926860X17303460|10.1016/j.apcata.2017.07.036      |2017    |CENG     |Chemical Engineering                        |Vapor-phase transport (VPT) modification of ZSM-5/SiC foam catalyst using TPAOH vapor to improve the methanol-to-propylene (MTP) reaction                                                                                       |
|S0032591019310253|10.1016/j.powtec.2019.11.064      |2020    |CENG     |Chemical Engineering                        |Manufacture of fine cellulose powder from chemically crosslinked kraft pulp sheets using dry milling                                                                                                                            |
|S0032591018305278|10.1016/j.powtec.2018.07.030      |2018    |CENG     |Chemical Engineering                        |Jamming during particle spreading in additive manufacturing                                                                                                                                                                     |
|S0926860X19301851|10.1016/j.apcata.2019.04.026      |2019    |CENG     |Chemical Engineering                        |Kinetics of long chain n-paraffin dehydrogenation over a commercial Pt-Sn-K-Mg/Γ-Al2O3 catalyst: Model studies using n-dodecane                                                                                                 |
|S0032591019311283|10.1016/j.powtec.2019.12.023      |2020    |CENG     |Chemical Engineering                        |Numerical simulation of particle flow and segregation during roller spreading process in additive manufacturing                                                                                                                 |
|S0032591019306059|10.1016/j.powtec.2019.08.006      |2019    |CENG     |Chemical Engineering                        |Fluid-solid interaction simulation for particles and walls of arbitrary polygonal shapes with a coupled LBM-IMB-DEM method                                                                                                      |
|S0926860X16304203|10.1016/j.apcata.2016.08.013      |2016    |CENG     |Chemical Engineering                        |Temperature-programmed reduction of nickel steam reforming catalyst with glucose                                                                                                                                                |
|S0032591018302523|10.1016/j.powtec.2018.03.059      |2018    |CENG     |Chemical Engineering                        |Quantifying the contact electrification of aerosolized insulating particles                                                                                                                                                     |
|S0926860X17300893|10.1016/j.apcata.2017.02.023      |2017    |CENG     |Chemical Engineering                        |SiO2-supported Fe & FeMn colloids—Fischer-Tropsch synthesis on 3D model catalysts                                                                                                                                               |
|S0926860X18300632|10.1016/j.apcata.2018.02.005      |2018    |CENG     |Chemical Engineering                        |PdZn nanoparticle catalyst formation for ethanol dehydrogenation: Active metal impregnation vs incorporation                                                                                                                    |
|S0143720817316856|10.1016/j.dyepig.2017.09.071      |2018    |CENG     |Chemical Engineering                        |Thermochromic behaviors of boron–magnesium co-doped BiVO4 powders prepared by a hydrothermal method                                                                                                                             |
|S0032591014005245|10.1016/j.powtec.2014.05.057      |2014    |CENG     |Chemical Engineering                        |Numerical analysis of particle flows within a double expansion                                                                                                                                                                  |
|S0032591018304455|10.1016/j.powtec.2018.06.011      |2018    |CENG     |Chemical Engineering                        |Measuring attrition properties of calcium looping materials in a 30 kW pilot plant                                                                                                                                              |
|S0926860X17305690|10.1016/j.apcata.2017.12.014      |2018    |CENG     |Chemical Engineering                        |“Metal-free” electrocatalysis: Quaternary-doped graphene and the alkaline oxygen reduction reaction                                                                                                                             |
|S2451904917304833|10.1016/j.tsep.2018.09.003        |2018    |CENG     |Chemical Engineering                        |Performance of evacuated flat plate solar thermal collectors                                                                                                                                                                    |
|S2451904917302731|10.1016/j.tsep.2017.09.009        |2017    |CENG     |Chemical Engineering                        |Development and analysis of a packaged Trilateral Flash Cycle system for low grade heat to power conversion applications                                                                                                        |
|S0926860X17304738|10.1016/j.apcata.2017.09.032      |2018    |CENG     |Chemical Engineering                        |Hydrogenation of levulinic acid to Γ-valerolactone over anatase-supported Ru catalysts: Effect of catalyst synthesis protocols on activity                                                                                      |
|S0032591017301511|10.1016/j.powtec.2017.02.024      |2017    |CENG     |Chemical Engineering                        |A review of bulk powder caking                                                                                                                                                                                                  |
|S0926860X18305532|10.1016/j.apcata.2018.11.006      |2019    |CENG     |Chemical Engineering                        |Novel rhodium on carbon catalysts for the oxidation of benzyl alcohol to benzaldehyde: A study of the modification of metal/support interactions by acid pre-treatments                                                         |
|S0143720814003842|10.1016/j.dyepig.2014.09.025      |2015    |CENG     |Chemical Engineering                        |The aggregation-induced emission enhancement properties of BF2 complex isatin-phenylhydrazone: Synthesis and fluorescence characteristics                                                                                       |
|S0039914018312529|10.1016/j.talanta.2018.11.100     |2019    |CHEM     |Chemistry                                   |Which cocoa bean traits persist when eating chocolate? Real-time nosespace analysis by PTR-QiToF-MS                                                                                                                             |
|S1388248119300360|10.1016/j.elecom.2019.01.028      |2019    |CHEM     |Chemistry                                   |Plasma-etching enhanced titanium oxynitride active phase with high oxygen content for ambient electrosynthesis of ammonia                                                                                                       |
|S2405830019302447|10.1016/j.cdc.2019.100280         |2019    |CHEM     |Chemistry                                   |Performance evaluation of zinc anodes for cathodic protection of mild steel corrosion in HCL                                                                                                                                    |
|S1388248119303078|10.1016/j.elecom.2019.106644      |2020    |CHEM     |Chemistry                                   |Ex-situ visualization of the wet domain in the microporous layer in a polymer electrolyte fuel cell by X-ray computed tomography under water vapor supply                                                                       |
|S0165993618306356|10.1016/j.trac.2019.02.024        |2020    |CHEM     |Chemistry                                   |Towards a comprehensive analytical workflow for the chemical characterisation of organofluorine in consumer products and environmental samples                                                                                  |
|S1388248118302935|10.1016/j.elecom.2018.11.008      |2019    |CHEM     |Chemistry                                   |Click chemistry on azide-functionalized graphene oxide                                                                                                                                                                          |
|S2376999816300137|10.1016/j.clinms.2016.12.001      |2016    |CHEM     |Chemistry                                   |Quantitation of total fatty acids in plasma and serum by GC-NCI-MS                                                                                                                                                              |
|S2376999816300204|10.1016/j.clinms.2016.12.003      |2016    |CHEM     |Chemistry                                   |A proposal to improve calibration and outlier detection in high-throughput mass spectrometry                                                                                                                                    |
|S1388248116303113|10.1016/j.elecom.2016.12.011      |2017    |CHEM     |Chemistry                                   |Transition metal-nitrogen-carbon catalysts for oxygen reduction reaction in neutral electrolyte                                                                                                                                 |
|S003991401731024X|10.1016/j.talanta.2017.09.081     |2018    |CHEM     |Chemistry                                   |Development and evaluation of a new diffusive gradients in thin-films technique for measuring organotin compounds in coastal sediment pore water                                                                                |
|S0039914016306634|10.1016/j.talanta.2016.08.078     |2016    |CHEM     |Chemistry                                   |Simultaneous capture and sequential detection of two malarial biomarkers on magnetic microparticles                                                                                                                             |
|S0039914019310239|10.1016/j.talanta.2019.120390     |2019    |CHEM     |Chemistry                                   |Vacuum-assisted sorbent extraction: An analytical methodology for the determination of ultraviolet filters in environmental samples                                                                                             |
|S0165993616302199|10.1016/j.trac.2016.10.010        |2017    |CHEM     |Chemistry                                   |Fingerprinting outdoor air environment using microbial volatile organic compounds (MVOCs) – A review                                                                                                                            |
|S0022286016304136|10.1016/j.molstruc.2016.04.077    |2016    |CHEM     |Chemistry                                   |Crystal structure resolution of two different chlorhexidine salts                                                                                                                                                               |
|S1388248119302796|10.1016/j.elecom.2019.106616      |2020    |CHEM     |Chemistry                                   |Low resistance, highly corrugated structures based on poly(3,4-ethylenedioxythiophene) doped with a D-glucopyranoside-derived ionic liquid                                                                                      |
|S1388248119300554|10.1016/j.elecom.2019.02.019      |2019    |CHEM     |Chemistry                                   |Efficient detection of localized corrosion processes on stainless steel by means of scanning electrochemical microscopy (SECM) using a multi-electrode approach                                                                 |
|S1388248119302267|10.1016/j.elecom.2019.106563      |2019    |CHEM     |Chemistry                                   |Fabricating copper and copper/nickel alloy single crystal bead electrodes with a hydrogen–oxygen torch in ambient air                                                                                                           |
|S0026265X15003331|10.1016/j.microc.2015.11.053      |2016    |CHEM     |Chemistry                                   |A multi-analytical approach towards the investigation of Subarctic Athapaskan colouring of quillwork and its sensitivity to photo-degradation                                                                                   |
|S1388248118303084|10.1016/j.elecom.2018.11.017      |2019    |CHEM     |Chemistry                                   |Negative capacitance or inductive loop? – A general assessment of a common low frequency impedance feature                                                                                                                      |
|S2405830019303842|10.1016/j.cdc.2019.100312         |2020    |CHEM     |Chemistry                                   |Solid-phase extraction and high performance liquid chromatography with diode array detection method for the determination of antibiotic residues in poultry tissues                                                             |
|S0031320319301608|10.1016/j.patcog.2019.04.014      |2019    |COMP     |Computer Science                            |How much can k-means be improved by using better initialization and repeats?                                                                                                                                                    |
|S1383762119304643|10.1016/j.sysarc.2019.101657      |2019    |COMP     |Computer Science                            |Verifying parallel dataflow transformations with model checking and its application to FPGAs                                                                                                                                    |
|S1389128618300677|10.1016/j.comnet.2018.01.050      |2018    |COMP     |Computer Science                            |Internet traffic characterisation: Third-order statistics & higher-order spectra for precise traffic modelling                                                                                                                  |
|S2352711018300980|10.1016/j.softx.2019.04.002       |2019    |COMP     |Computer Science                            |Itinerum: The open smartphone travel survey platform                                                                                                                                                                            |
|S2352711017300080|10.1016/j.softx.2017.04.001       |2017    |COMP     |Computer Science                            |MGtoolkit: A python package for implementing metagraphs                                                                                                                                                                         |
|S0164121215002010|10.1016/j.jss.2015.08.053         |2016    |COMP     |Computer Science                            |The influence of developer multi-homing on competition between software ecosystems                                                                                                                                              |
|S0306437915000459|10.1016/j.is.2015.02.007          |2015    |COMP     |Computer Science                            |Compliance monitoring in business processes: Functionalities, application, and tool-support                                                                                                                                     |
|S0167865518305099|10.1016/j.patrec.2019.08.026      |2019    |COMP     |Computer Science                            |Doubly Stochastic Neighbor Embedding on Spheres                                                                                                                                                                                 |
|S0167865515001531|10.1016/j.patrec.2015.05.008      |2015    |COMP     |Computer Science                            |Parallel selective sampling method for imbalanced and large data classification                                                                                                                                                 |
|S1077314215002040|10.1016/j.cviu.2015.09.009        |2016    |COMP     |Computer Science                            |On detecting the playing/non-playing activity of musicians in symphonic music videos                                                                                                                                            |
|S2352711018302164|10.1016/j.softx.2019.01.007       |2019    |COMP     |Computer Science                            |EOF-Library: Open-source Elmer FEM and OpenFOAM coupler for electromagnetics and fluid dynamics                                                                                                                                 |
|S1574119217305382|10.1016/j.pmcj.2017.11.002        |2018    |COMP     |Computer Science                            |Consume: A privacy-preserving authorisation and authentication service for connecting with health and wellbeing APIs                                                                                                            |
|S0164121215000151|10.1016/j.jss.2015.01.020         |2015    |COMP     |Computer Science                            |Diagrams or structural lists in software project retrospectives - An experimental comparison                                                                                                                                    |
|S1389128617300464|10.1016/j.comnet.2017.02.008      |2017    |COMP     |Computer Science                            |Survey on peer-assisted content delivery networks                                                                                                                                                                               |
|S0031320316301224|10.1016/j.patcog.2016.06.005      |2017    |COMP     |Computer Science                            |Learning scale-variant and scale-invariant features for deep image classification                                                                                                                                               |
|S1570870518300763|10.1016/j.adhoc.2018.04.003       |2018    |COMP     |Computer Science                            |Dynamic Neighbour Aware Power-controlled MAC for Multi-hop Ad-hoc networks                                                                                                                                                      |
|S2352711016300024|10.1016/j.softx.2016.03.001       |2016    |COMP     |Computer Science                            |Water cycle algorithm: A detailed standard code                                                                                                                                                                                 |
|S2352711017300304|10.1016/j.softx.2017.07.007       |2017    |COMP     |Computer Science                            |Hermes: Seamless delivery of containerized bioinformatics workflows in hybrid cloud (HTC) environments                                                                                                                          |
|S0164121219302262|10.1016/j.jss.2019.110452         |2020    |COMP     |Computer Science                            |Maintaining interoperability in open source software: A case study of the Apache PDFBox project                                                                                                                                 |
|S2352711018300797|10.1016/j.softx.2018.05.002       |2018    |COMP     |Computer Science                            |DEIP, discontinuous element insertion Program — Mesh generation for interfacial finite element modeling                                                                                                                         |
|S0965856418307134|10.1016/j.tra.2018.12.010         |2019    |DECI     |Decision Sciences                           |The importance of user perspective in the evolution of MaaS                                                                                                                                                                     |
|S2589750019301591|10.1016/S2589-7500(19)30159-1     |2019    |DECI     |Decision Sciences                           |Prediction of lung cancer risk at follow-up screening with low-dose CT: a training and validation study of a deep learning method                                                                                               |
|S2590198219300144|10.1016/j.trip.2019.100014        |2019    |DECI     |Decision Sciences                           |What passengers really want: Assessing the value of rail innovation to improve experiences                                                                                                                                      |
|S0965856416302208|10.1016/j.tra.2016.03.010         |2016    |DECI     |Decision Sciences                           |Comparing high-end and low-end early adopters of battery electric vehicles                                                                                                                                                      |
|S258975001930130X|10.1016/S2589-7500(19)30130-X     |2019    |DECI     |Decision Sciences                           |A co-designed mHealth programme to support healthy lifestyles in Māori and Pasifika peoples in New Zealand (OL@-OR@): a cluster-randomised controlled trial                                                                     |
|S0965856416307170|10.1016/j.tra.2017.03.009         |2017    |DECI     |Decision Sciences                           |Development of joint models for channel, store, and travel mode choice: Grocery shopping in London                                                                                                                              |
|S0965856419306858|10.1016/j.tra.2019.11.030         |2020    |DECI     |Decision Sciences                           |The effects of susceptibility, eco-friendliness and dependence on the Consumers’ Willingness to Pay for a door-to-door DRT system                                                                                               |
|S0965856417304731|10.1016/j.tra.2018.04.002         |2018    |DECI     |Decision Sciences                           |Vulnerability to fuel price increases in the UK: A household level analysis                                                                                                                                                     |
|S096585641730352X|10.1016/j.tra.2018.03.027         |2018    |DECI     |Decision Sciences                           |Identifying road user classes based on repeated trip behaviour using Bluetooth data                                                                                                                                             |
|S0965856415301865|10.1016/j.tra.2017.03.007         |2017    |DECI     |Decision Sciences                           |Electrically-assisted bikes: Potential impacts on travel behaviour                                                                                                                                                              |
|S2589750019300822|10.1016/S2589-7500(19)30082-2     |2019    |DECI     |Decision Sciences                           |Chat-based instant messaging support integrated with brief interventions for smoking cessation: a community-based, pragmatic, cluster-randomised controlled trial                                                               |
|S0965856418315751|10.1016/j.tra.2019.04.011         |2019    |DECI     |Decision Sciences                           |Exploring parental perceptions about school travel and walking school buses: A thematic analysis approach                                                                                                                       |
|S2589750019301281|10.1016/S2589-7500(19)30128-1     |2019    |DECI     |Decision Sciences                           |Innovative intelligent insole system reduces diabetic foot ulcer recurrence at plantar sites: a prospective, randomised, proof-of-concept study                                                                                 |
|S0965856414001189|10.1016/j.tra.2014.05.004         |2014    |DECI     |Decision Sciences                           |Energy efficiency and time charter rates: Energy efficiency savings recovered by ship owners in the Panamax market                                                                                                              |
|S0965856417314866|10.1016/j.tra.2018.05.018         |2019    |DECI     |Decision Sciences                           |Impacts of an active travel intervention with a cycling focus in a suburban context: One-year findings from an evaluation of London's in-progress mini-Hollands programme                                                       |
|S0167668717304262|10.1016/j.insmatheco.2017.09.011  |2018    |DECI     |Decision Sciences                           |The double-gap life expectancy forecasting model                                                                                                                                                                                |
|S2589750019300573|10.1016/S2589-7500(19)30057-3     |2019    |DECI     |Decision Sciences                           |The effects and preventability of 2627 patient safety incidents related to health information technology failures: a retrospective analysis of 10 years of incident reporting in England and Wales                              |
|S2589750019301086|10.1016/S2589-7500(19)30108-6     |2019    |DECI     |Decision Sciences                           |Automated deep learning design for medical image classification by health-care professionals with no coding experience: a feasibility study                                                                                     |
|S0965856416304888|10.1016/j.tra.2017.01.019         |2017    |DECI     |Decision Sciences                           |5 years of Dutch eco-driving: Managing behavioural change                                                                                                                                                                       |
|S2589750019300883|10.1016/S2589-7500(19)30088-3     |2019    |DECI     |Decision Sciences                           |Effectiveness of school-based eHealth interventions to prevent multiple lifestyle risk behaviours among adolescents: a systematic review and meta-analysis                                                                      |
|S1044028316300941|10.1016/j.gfj.2017.03.004         |2017    |ECON     |Economics, Econometrics and Finance         |Mergers and acquisitions in Germany: 1981–2010                                                                                                                                                                                  |
|S1057521918306665|10.1016/j.irfa.2019.101381        |2019    |ECON     |Economics, Econometrics and Finance         |Global and regional stock market integration in Asia: A panel convergence approach                                                                                                                                              |
|S026499931731800X|10.1016/j.econmod.2018.06.016     |2018    |ECON     |Economics, Econometrics and Finance         |Assessing the economic and social impact of tax and benefit reforms: A general-equilibrium microsimulation approach applied to Hungary                                                                                          |
|S0047272717301299|10.1016/j.jpubeco.2017.08.008     |2017    |ECON     |Economics, Econometrics and Finance         |The effects of access to health insurance: Evidence from a regression discontinuity design in Peru                                                                                                                              |
|S0165176516304190|10.1016/j.econlet.2016.10.036     |2017    |ECON     |Economics, Econometrics and Finance         |Which firms use Islamic financing?                                                                                                                                                                                              |
|S0928765519301186|10.1016/j.reseneeco.2019.101124   |2020    |ECON     |Economics, Econometrics and Finance         |Who benefits from China's coal subsidy policies? A computable partial equilibrium analysis                                                                                                                                      |
|S1042443115001043|10.1016/j.intfin.2015.09.003      |2016    |ECON     |Economics, Econometrics and Finance         |The impacts of risk and competition on bank profitability in China                                                                                                                                                              |
|S0147596719300629|10.1016/j.jce.2019.07.001         |2019    |ECON     |Economics, Econometrics and Finance         |The economic contribution of the “C” in ICT: Evidence from OECD countries                                                                                                                                                       |
|S0165176516302944|10.1016/j.econlet.2016.08.009     |2016    |ECON     |Economics, Econometrics and Finance         |The contribution of firm-level shocks to aggregate fluctuations: The case of Sweden                                                                                                                                             |
|S2405851319300789|10.1016/j.jcomm.2019.100113       |2020    |ECON     |Economics, Econometrics and Finance         |New generation grain contracts in corn and soybean commodity markets                                                                                                                                                            |
|S0047272717302086|10.1016/j.jpubeco.2017.12.006     |2018    |ECON     |Economics, Econometrics and Finance         |Empty homes, longer commutes: The unintended consequences of more restrictive local planning                                                                                                                                    |
|S0161893819300882|10.1016/j.jpolmod.2019.06.004     |2019    |ECON     |Economics, Econometrics and Finance         |The economic benefits of the EU Single Market in goods and services                                                                                                                                                             |
|S0261560617301833|10.1016/j.jimonfin.2017.09.006    |2018    |ECON     |Economics, Econometrics and Finance         |Reduced cross-border lending and financing costs of SMEs                                                                                                                                                                        |
|S0047272717300361|10.1016/j.jpubeco.2017.03.002     |2017    |ECON     |Economics, Econometrics and Finance         |Growth and inequality in public good provision                                                                                                                                                                                  |
|S0014292117301010|10.1016/j.euroecorev.2017.06.001  |2017    |ECON     |Economics, Econometrics and Finance         |The importance of peers for compliance with norms of fair sharing                                                                                                                                                               |
|S0164070415000208|10.1016/j.jmacro.2015.01.002      |2015    |ECON     |Economics, Econometrics and Finance         |Fiscal multipliers in good times and bad times                                                                                                                                                                                  |
|S1572308917304291|10.1016/j.jfs.2017.06.005         |2018    |ECON     |Economics, Econometrics and Finance         |Identifying excessive credit growth and leverage                                                                                                                                                                                |
|S1057521918301650|10.1016/j.irfa.2018.11.012        |2019    |ECON     |Economics, Econometrics and Finance         |Business cycle synchronisation and currency unions: A review of the econometric evidence using meta-analysis                                                                                                                    |
|S0165176519303337|10.1016/j.econlet.2019.108668     |2019    |ECON     |Economics, Econometrics and Finance         |In search of attention in agricultural commodity markets                                                                                                                                                                        |
|S0378426617301711|10.1016/j.jbankfin.2017.07.011    |2017    |ECON     |Economics, Econometrics and Finance         |Analysing the determinants of insolvency risk for general insurance firms in the UK                                                                                                                                             |
|S0378778816304558|10.1016/j.enbuild.2016.05.077     |2016    |ENGI     |Engineering                                 |On the application of wireless sensors and actuators network in existing buildings for occupancy detection and occupancy-driven lighting control                                                                                |
|S0378778818304146|10.1016/j.enbuild.2018.06.058     |2018    |ENGI     |Engineering                                 |Interactive visualization for NILM in large buildings using non-negative matrix factorization                                                                                                                                   |
|S0140700717301329|10.1016/j.ijrefrig.2017.03.024    |2017    |ENGI     |Engineering                                 |Two-phase frictional pressure drop in horizontal micro-scale channels: Experimental data analysis and prediction method development                                                                                             |
|S0167473016301904|10.1016/j.strusafe.2018.02.002    |2018    |ENGI     |Engineering                                 |Weibull parameter estimation and goodness-of-fit for glass strength data                                                                                                                                                        |
|S0141029616312561|10.1016/j.engstruct.2017.05.004   |2017    |ENGI     |Engineering                                 |Distortional analysis of simply supported box girders with inner diaphragms considering shear deformation of diaphragms using initial parameter method                                                                          |
|S014070071830032X|10.1016/j.ijrefrig.2018.02.001    |2018    |ENGI     |Engineering                                 |Numerical modeling of a two-phase twin-screw expander for Trilateral Flash Cycle applications                                                                                                                                   |
|S0141029617339755|10.1016/j.engstruct.2018.09.064   |2018    |ENGI     |Engineering                                 |Strength and deflection behaviour of cold-formed steel back-to-back channels                                                                                                                                                    |
|S1110016819300274|10.1016/j.aej.2019.04.002         |2019    |ENGI     |Engineering                                 |An experimental and theoretical study on particles-in-air behavior characterization at different particles loading and turbulence modulation                                                                                    |
|S0140700716304170|10.1016/j.ijrefrig.2016.12.005    |2017    |ENGI     |Engineering                                 |Thermodynamic modelling and parameter determination of ejector for ejection refrigeration systems                                                                                                                               |
|S0378778816302158|10.1016/j.enbuild.2016.03.059     |2016    |ENGI     |Engineering                                 |Building energy metering and environmental monitoring - A state-of-the-art review and directions for future research                                                                                                            |
|S1270963818315372|10.1016/j.ast.2019.03.032         |2019    |ENGI     |Engineering                                 |A Statistical Energy Analysis (SEA) model of a fuselage section for the prediction of the internal Sound Pressure Level (SPL) at cruise flight conditions                                                                       |
|S0208521618302365|10.1016/j.bbe.2018.08.005         |2018    |ENGI     |Engineering                                 |Fuzzy genetic-based noise removal filter for digital panoramic X-ray images                                                                                                                                                     |
|S0263823117308017|10.1016/j.tws.2018.01.020         |2018    |ENGI     |Engineering                                 |Experimental investigation of local-flexural interactive buckling of cold-formed steel channel columns                                                                                                                          |
|S0951832015003567|10.1016/j.ress.2015.12.004        |2016    |ENGI     |Engineering                                 |A model for availability growth with application to new generation offshore wind farms                                                                                                                                          |
|S0007850616301949|10.1016/j.cirp.2016.06.002        |2016    |ENGI     |Engineering                                 |Closed-loop control of product properties in metal forming                                                                                                                                                                      |
|S0141118716305764|10.1016/j.apor.2016.12.006        |2017    |ENGI     |Engineering                                 |Design optimisation of Propeller Boss Cap Fins for enhanced propeller performance                                                                                                                                               |
|S0378778819322285|10.1016/j.enbuild.2019.109498     |2019    |ENGI     |Engineering                                 |The specific contributions of activities to household electricity demand                                                                                                                                                        |
|S0378778817314342|10.1016/j.enbuild.2017.04.059     |2017    |ENGI     |Engineering                                 |Heating behaviour in English homes: An assessment of indirect calculation methods                                                                                                                                               |
|S0141029615001388|10.1016/j.engstruct.2015.03.003   |2015    |ENGI     |Engineering                                 |Experimental characterisation of walking locomotion on rigid level surfaces using motion capture system                                                                                                                         |
|S0378778817322612|10.1016/j.enbuild.2017.09.013     |2017    |ENGI     |Engineering                                 |‘Hitting the target and missing the point’: Analysis of air permeability data for new UK dwellings and what it reveals about the testing procedure                                                                              |
|S0160412017309005|10.1016/j.envint.2017.09.013      |2017    |ENVI     |Environmental Science                       |Integrating human and environmental health in antibiotic risk assessment: A critical analysis of protection goals, species sensitivity and antimicrobial resistance                                                             |
|S0160412018313230|10.1016/j.envint.2018.11.044      |2019    |ENVI     |Environmental Science                       |Human biomonitoring in Australian children: Brominated flame retardants decrease from 2006 to 2015                                                                                                                              |
|S0048969718323489|10.1016/j.scitotenv.2018.06.272   |2018    |ENVI     |Environmental Science                       |Behaviour and fate of vanadium during the aerobic neutralisation of hyperalkaline slag leachate                                                                                                                                 |
|S0048969719326385|10.1016/j.scitotenv.2019.06.070   |2019    |ENVI     |Environmental Science                       |Multi-objective optimization as a tool to identify possibilities for future agricultural landscapes                                                                                                                             |
|S0169204617303237|10.1016/j.landurbplan.2017.12.002 |2018    |ENVI     |Environmental Science                       |Perceived species-richness in urban green spaces: Cues, accuracy and well-being impacts                                                                                                                                         |
|S0048969715308111|10.1016/j.scitotenv.2015.09.150   |2016    |ENVI     |Environmental Science                       |Role of an organic carbon-rich soil and Fe(III) reduction in reducing the toxicity and environmental mobility of chromium(VI) at a COPR disposal site                                                                           |
|S0048969718331322|10.1016/j.scitotenv.2018.08.168   |2019    |ENVI     |Environmental Science                       |Putting on a bow-tie to sort out who does what and why in the complex arena of marine policy and management                                                                                                                     |
|S0048969719309064|10.1016/j.scitotenv.2019.02.398   |2019    |ENVI     |Environmental Science                       |Source specific exposure and risk assessment for indoor aerosols                                                                                                                                                                |
|S0169204618307497|10.1016/j.landurbplan.2019.05.012 |2019    |ENVI     |Environmental Science                       |Using GIS-linked Bayesian Belief Networks as a tool for modelling urban biodiversity                                                                                                                                            |
|S2589915519300252|10.1016/j.hydroa.2019.100041      |2019    |ENVI     |Environmental Science                       |Timescales of water-quality change in a karst aquifer, south-central Texas                                                                                                                                                      |
|S0301479719308461|10.1016/j.jenvman.2019.06.037     |2019    |ENVI     |Environmental Science                       |Development of a pragmatic framework to help food and drink manufacturers select the most sustainable food waste valorisation strategy                                                                                          |
|S0160412018306810|10.1016/j.envint.2019.01.020      |2019    |ENVI     |Environmental Science                       |Early-life exposure to persistent organic pollutants (OCPs, PBDEs, PCBs, PFASs) and attention-deficit/hyperactivity disorder: A multi-pollutant analysis of a Norwegian birth cohort                                            |
|S0043135419303367|10.1016/j.watres.2019.04.028      |2019    |ENVI     |Environmental Science                       |The cooling tower water microbiota: Seasonal dynamics and co-occurrence of bacterial and protist phylotypes                                                                                                                     |
|S0048969716314632|10.1016/j.scitotenv.2016.07.018   |2016    |ENVI     |Environmental Science                       |Tectonic and climatic considerations for deep geological disposal of radioactive waste: A UK perspective                                                                                                                        |
|S0160412019313558|10.1016/j.envint.2019.06.010      |2019    |ENVI     |Environmental Science                       |Assessment of recycled ceramic-based inorganic insulation for improving energy efficiency and flame retardancy of buildings                                                                                                     |
|S0043135418305566|10.1016/j.watres.2018.07.017      |2018    |ENVI     |Environmental Science                       |High-silica zeolites for adsorption of organic micro-pollutants in water treatment: A review                                                                                                                                    |
|S0309170818301295|10.1016/j.advwatres.2018.11.011   |2019    |ENVI     |Environmental Science                       |Numerical simulation of floods from multiple sources using an adaptive anisotropic unstructured mesh method                                                                                                                     |
|S0304380014003664|10.1016/j.ecolmodel.2014.07.029   |2014    |ENVI     |Environmental Science                       |Simulating 2368 temperate lakes reveals weak coherence in stratification phenology                                                                                                                                              |
|S0160412019306038|10.1016/j.envint.2019.05.050      |2019    |ENVI     |Environmental Science                       |Should dsRNA treatments applied in outdoor environments be regulated?                                                                                                                                                           |
|S0043135418306274|10.1016/j.watres.2018.08.006      |2018    |ENVI     |Environmental Science                       |Informing public attitudes to non-potable water reuse – The impact of message framing                                                                                                                                           |
|S089219971730036X|10.1016/j.jvoice.2017.03.013      |2017    |HEAL     |Health Professions                          |Biomechanical Flow Amplification Arising From the Variable Deformation of the Subglottic Mucosa                                                                                                                                 |
|S0892199718301747|10.1016/j.jvoice.2018.06.011      |2020    |HEAL     |Health Professions                          |A Longitudinal Study Investigating Synchronization in a Singing Quintet                                                                                                                                                         |
|S0031940618303468|10.1016/j.physio.2018.11.005      |2019    |HEAL     |Health Professions                          |The motivations and aspirations of Indian physiotherapists who migrate overseas to study and work: a grounded theory study                                                                                                      |
|S0003999318300856|10.1016/j.apmr.2018.01.012        |2018    |HEAL     |Health Professions                          |Creation and Initial Validation of the International Dysphagia Diet Standardisation Initiative Functional Diet Scale                                                                                                            |
|S0031940618303432|10.1016/j.physio.2018.11.002      |2019    |HEAL     |Health Professions                          |Associations between activity and participation in adults with multiple sclerosis: a cross sectional study                                                                                                                      |
|S1550830713003017|10.1016/j.explore.2013.10.005     |2014    |HEAL     |Health Professions                          |Intention-based therapy for autism spectrum disorder: Promising results of a wait-list control study in children                                                                                                                |
|S0031940619300367|10.1016/j.physio.2019.01.015      |2020    |HEAL     |Health Professions                          |PALS: peer support for community dwelling older people with chronic low back pain: a feasibility and acceptability study                                                                                                        |
|S0892199716300042|10.1016/j.jvoice.2016.05.015      |2017    |HEAL     |Health Professions                          |Expiratory and Inspiratory Cries Detection Using Different Signals’ Decomposition Techniques                                                                                                                                    |
|S1440244016301517|10.1016/j.jsams.2016.08.008       |2017    |HEAL     |Health Professions                          |Validation of thigh-based accelerometer estimates of postural allocation in 5–12 year-olds                                                                                                                                      |
|S0031940618303249|10.1016/j.physio.2019.08.013      |2020    |HEAL     |Health Professions                          |Validity of the International Physical Activity Questionnaire Short Form (IPAQ-SF) as a measure of physical activity (PA) in young people with cerebral palsy: A cross-sectional study                                          |
|S1440244014002035|10.1016/j.jsams.2014.10.003       |2016    |HEAL     |Health Professions                          |Changes in time-segment specific physical activity between ages 10 and 14 years: A longitudinal observational study                                                                                                             |
|S0892199718302418|10.1016/j.jvoice.2018.07.015      |2020    |HEAL     |Health Professions                          |A Longitudinal Study of Intonation in an a cappella Singing Quintet                                                                                                                                                             |
|S0021992418300789|10.1016/j.jcomdis.2019.105915     |2019    |HEAL     |Health Professions                          |“Spontaneous” late recovery from stuttering: Dimensions of reported techniques and causal attributions                                                                                                                          |
|S144024401830971X|10.1016/j.jsams.2019.03.004       |2019    |HEAL     |Health Professions                          |The prevalence of hand and wrist osteoarthritis in elite former cricket and rugby union players                                                                                                                                 |
|S0892199716304039|10.1016/j.jvoice.2017.01.005      |2017    |HEAL     |Health Professions                          |A Simplified Vocal Profile Analysis Protocol for the Assessment of Voice Quality and Speaker Similarity                                                                                                                         |
|S0892199718301899|10.1016/j.jvoice.2018.09.006      |2018    |HEAL     |Health Professions                          |Effects of the Lung Volume on the Electroglottographic Waveform in Trained Female Singers                                                                                                                                       |
|S1440244016302389|10.1016/j.jsams.2016.11.003       |2017    |HEAL     |Health Professions                          |Physical activity and sedentary time in relation to academic achievement in children                                                                                                                                            |
|S0031940617300020|10.1016/j.physio.2017.01.001      |2017    |HEAL     |Health Professions                          |Physiotherapy interventions for people with dementia and a hip fracture—a scoping review of the literature                                                                                                                      |
|S0031940619300781|10.1016/j.physio.2019.07.002      |2020    |HEAL     |Health Professions                          |Development and implementation of the physiotherapy-led exercise interventions for the treatment of rotator cuff disorders for the ‘Getting it Right: Addressing Shoulder Pain’ (GRASP) trial                                   |
|S1356689X1400229X|10.1016/j.math.2014.11.008        |2015    |HEAL     |Health Professions                          |Clinical challenges of classification based targeted therapies for non-specific low back pain: What do physiotherapy practitioners and managers think?                                                                          |
|S193131281730032X|10.1016/j.chom.2017.01.010        |2017    |IMMU     |Immunology and Microbiology                 |Conserved Fever Pathways across Vertebrates: A Herpesvirus Expressed Decoy TNF-α Receptor Delays Behavioral Fever in Fish                                                                                                       |
|S2211283914000070|10.1016/j.rinim.2014.06.001       |2014    |IMMU     |Immunology and Microbiology                 |Normal serum levels of immune complexes in postpolio patients                                                                                                                                                                   |
|S1879625716301882|10.1016/j.coviro.2016.11.008      |2017    |IMMU     |Immunology and Microbiology                 |Capturing norovirus transmission                                                                                                                                                                                                |
|S0042682219303083|10.1016/j.virol.2019.10.019       |2020    |IMMU     |Immunology and Microbiology                 |Field porcine reproductive and respiratory syndrome viruses (PRRSV) attenuated by codon pair deoptimization (CPD) in NSP1 protected pigs from heterologous challenge                                                            |
|S2211283916300028|10.1016/j.rinim.2016.02.001       |2016    |IMMU     |Immunology and Microbiology                 |Immunomodulation for treatment of drug and device refractory gastroparesis                                                                                                                                                      |
|S1931312815000244|10.1016/j.chom.2015.01.004        |2015    |IMMU     |Immunology and Microbiology                 |The C-type lectin receptor CLECSF8/CLEC4D is a key component of anti-mycobacterial immunity                                                                                                                                     |
|S1931312815002504|10.1016/j.chom.2015.05.018        |2015    |IMMU     |Immunology and Microbiology                 |Conditional degradation of plasmodium calcineurin reveals functions in parasite colonization of both host and vector                                                                                                            |
|S1931312818304876|10.1016/j.chom.2018.09.003        |2018    |IMMU     |Immunology and Microbiology                 |Partially Open HIV-1 Envelope Structures Exhibit Conformational Changes Relevant for Coreceptor Binding and Fusion                                                                                                              |
|S0042682214005741|10.1016/j.virol.2014.12.025       |2015    |IMMU     |Immunology and Microbiology                 |An expanded taxonomy of hepatitis C virus genotype 6: Characterization of 22 new full-length viral genomes                                                                                                                      |
|S0166093418301058|10.1016/j.jviromet.2018.05.006    |2018    |IMMU     |Immunology and Microbiology                 |Development of fluorescent reverse transcription loop-mediated isothermal amplification (RT-LAMP) using quenching probes for the detection of the Middle East respiratory syndrome coronavirus                                  |
|S0166093415002906|10.1016/j.jviromet.2015.08.014    |2015    |IMMU     |Immunology and Microbiology                 |Optimization of Droplet Digital PCR from RNA and DNA extracts with direct comparison to RT-qPCR: Clinical implications for quantification of Oseltamivir-resistant subpopulations                                               |
|S0166093415002402|10.1016/j.jviromet.2015.07.007    |2015    |IMMU     |Immunology and Microbiology                 |Production of a Sindbis/Eastern Equine Encephalitis chimeric virus inactivated cell culture antigen                                                                                                                             |
|S1931312819302513|10.1016/j.chom.2019.05.006        |2019    |IMMU     |Immunology and Microbiology                 |A Genetically Tractable, Natural Mouse Model of Cryptosporidiosis Offers Insights into Host Protective Immunity                                                                                                                 |
|S004268221500313X|10.1016/j.virol.2015.07.004       |2015    |IMMU     |Immunology and Microbiology                 |Genotype-specific variation in West Nile virus dispersal in California                                                                                                                                                          |
|S0166093416303524|10.1016/j.jviromet.2016.12.007    |2017    |IMMU     |Immunology and Microbiology                 |Quantitative multi-target RNA profiling in Epstein-Barr virus infected tumor cells                                                                                                                                              |
|S1434461014000686|10.1016/j.protis.2014.07.003      |2014    |IMMU     |Immunology and Microbiology                 |The social amoeba polysphondylium pallidum loses encystation and sporulation, but can still erect fruiting bodies in the absence of cellulose                                                                                   |
|S0042682214005017|10.1016/j.virol.2014.11.007       |2015    |IMMU     |Immunology and Microbiology                 |RAB1A promotes Vaccinia virus replication by facilitating the production of intracellular enveloped virions                                                                                                                     |
|S1434461016000043|10.1016/j.protis.2016.01.003      |2016    |IMMU     |Immunology and Microbiology                 |Defining Planktonic Protist Functional Groups on Mechanisms for Energy and Nutrient Acquisition: Incorporation of Diverse Mixotrophic Strategies                                                                                |
|S004268221730017X|10.1016/j.virol.2017.01.008       |2017    |IMMU     |Immunology and Microbiology                 |Identification of rare HIV-1 Group N, HBV AE, and HTLV-3 strains in rural South Cameroon                                                                                                                                        |
|S0166093416300301|10.1016/j.jviromet.2016.04.012    |2016    |IMMU     |Immunology and Microbiology                 |Development of a reverse transcription loop-mediated isothermal amplification assay for the detection of vesicular stomatitis New Jersey virus: Use of rapid molecular assays to differentiate between vesicular disease viruses|
|S1359645418305998|10.1016/j.actamat.2018.07.059     |2018    |MATE     |Material Science                            |Crystallographic texture can be rapidly determined by electrochemical surface analytics                                                                                                                                         |
|S2214509518301888|10.1016/j.cscm.2018.e00192        |2018    |MATE     |Material Science                            |Seismic risk analysis of multistory reinforced concrete structures in Saudi Arabia                                                                                                                                              |
|S2468217918301801|10.1016/j.jsamd.2019.01.002       |2019    |MATE     |Material Science                            | Novel Ag-ZnO-La 2 O 2 CO 3 photocatalysts derived from the Layered Double Hydroxide structure with excellent photocatalytic performance for the degradation of pharmaceutical compounds                                        |
|S2468217916300612|10.1016/j.jsamd.2016.08.009       |2016    |MATE     |Material Science                            |High cycle fatigue behavior of the IN718/M247 hybrid element fabricated by friction welding at elevated temperatures                                                                                                            |
|S2468217916301873|10.1016/j.jsamd.2017.01.001       |2017    |MATE     |Material Science                            |Luminescence studies on the europium doped strontium metasilicate phosphor prepared by solid state reaction method                                                                                                              |
|S2214509517301353|10.1016/j.cscm.2018.e00189        |2018    |MATE     |Material Science                            |Effect of steel hanger height on its members’ internal forces due to wind loads: comparison between standards EN1991-1-4 and NV65                                                                                               |
|S2468217919302072|10.1016/j.jsamd.2019.07.005       |2019    |MATE     |Material Science                            |A new sustainable green protocol for production of reduced graphene oxide and its gas sensing properties                                                                                                                        |
|S1359645416304876|10.1016/j.actamat.2016.06.056     |2016    |MATE     |Material Science                            |A refining mechanism of primary Al3Ti intermetallic particles by ultrasonic treatment in the liquid state                                                                                                                       |
|S1359645417310248|10.1016/j.actamat.2017.12.019     |2018    |MATE     |Material Science                            |Individual effect of recrystallisation nucleation sites on texture weakening in a magnesium alloy: Part 2- shear bands                                                                                                          |
|S2468217919300085|10.1016/j.jsamd.2019.06.003       |2019    |MATE     |Material Science                            |Nanocellulose based functional materials for supercapacitor applications                                                                                                                                                        |
|S221450951730030X|10.1016/j.cscm.2017.04.001        |2017    |MATE     |Material Science                            |Corrosion of metals exposed to 25% magnesium chloride solution and tensile stress: Field and laboratory studies                                                                                                                 |
|S2468217918302144|10.1016/j.jsamd.2019.03.002       |2019    |MATE     |Material Science                            |Structural, optical, magnetic and thermal investigations on Cr3+ ions doped ZnS nanocrystals by co-precipitation method                                                                                                         |
|S2468217919300176|10.1016/j.jsamd.2019.02.004       |2019    |MATE     |Material Science                            |Polyacrylate polymer assisted crystallization: Improved charge transport and performance consistency for solution-processable small-molecule semiconductor based organic thin film transistors                                  |
|S2468217918302090|10.1016/j.jsamd.2018.11.003       |2018    |MATE     |Material Science                            |Physical properties of 2D and 3D ZnO materials fabricated by multi-methods and their photoelectric effect on organic solar cells                                                                                                |
|S095522191530114X|10.1016/j.jeurceramsoc.2015.08.032|2015    |MATE     |Material Science                            |Mechanical characterisation of a fibre reinforced oxide/oxide ceramic matrix composite                                                                                                                                          |
|S2468217917301648|10.1016/j.jsamd.2017.11.005       |2018    |MATE     |Material Science                            |Synthesis, characterization of bay-substituted perylene diimide based D-A-D type small molecules and their applications as a non-fullerene electron acceptor in polymer solar cells                                             |
|S2468217919302114|10.1016/j.jsamd.2019.08.003       |2019    |MATE     |Material Science                            |Study of interfaces in polymer-metal oxide films and free-volume hole using low-energy positron lifetime measurements                                                                                                           |
|S1359645418306748|10.1016/j.actamat.2018.08.037     |2018    |MATE     |Material Science                            |Direct volumetric measurement of crystallographic texture using acoustic waves                                                                                                                                                  |
|S2468217916301915|10.1016/j.jsamd.2016.12.003       |2017    |MATE     |Material Science                            |Analysis of microstructural effects on mechanical properties of copper alloys                                                                                                                                                   |
|S2214509514000096|10.1016/j.cscm.2014.04.003        |2014    |MATE     |Material Science                            |Ground penetrating radar utilization in exploring inadequate concrete covers in a new bridge deck                                                                                                                               |
|S0307904X17305206|10.1016/j.apm.2017.08.011         |2017    |MATH     |Mathematics                                 |A hybrid analytical-numerical method for solving water flow equations in root hydraulic architectures                                                                                                                           |
|S0307904X1930174X|10.1016/j.apm.2019.03.030         |2019    |MATH     |Mathematics                                 |Accounting for data sparsity when forming spatially coherent zones                                                                                                                                                              |
|S0960077918300213|10.1016/j.chaos.2018.01.021       |2018    |MATH     |Mathematics                                 |Complexity measures of music                                                                                                                                                                                                    |
|S0747717118300348|10.1016/j.jsc.2018.04.005         |2019    |MATH     |Mathematics                                 |Aligning concepts across proof assistant libraries                                                                                                                                                                              |
|S0307904X14004892|10.1016/j.apm.2014.10.016         |2015    |MATH     |Mathematics                                 |Thermal error modelling of machine tools based on ANFIS with fuzzy c-means clustering using a thermal imaging camera                                                                                                            |
|S0378437119316334|10.1016/j.physa.2019.122876       |2020    |MATH     |Mathematics                                 |Robustness of China's air transport network from 1975 to 2017                                                                                                                                                                   |
|S0307904X18301732|10.1016/j.apm.2018.04.001         |2018    |MATH     |Mathematics                                 |The impact of multi-layered porosity distribution on the performance of a lithium ion battery                                                                                                                                   |
|S0378437119301335|10.1016/j.physa.2019.01.126       |2019    |MATH     |Mathematics                                 |Green financial policies and capital flows                                                                                                                                                                                      |
|S0307904X19307553|10.1016/j.apm.2019.12.015         |2020    |MATH     |Mathematics                                 |An iterative elastic SBFE approach for collapse load analysis of inelastic structures                                                                                                                                           |
|S2590054419300041|10.1016/j.csfx.2019.100005        |2019    |MATH     |Mathematics                                 |Brain noise estimation from MEG response to flickering visual stimulation                                                                                                                                                       |
|S0997754615300352|10.1016/j.euromechflu.2016.02.005 |2016    |MATH     |Mathematics                                 |Development and validation of a procedure for numerical vibration analysis of an oscillating wave surge converter                                                                                                               |
|S009630031500171X|10.1016/j.amc.2015.02.018         |2016    |MATH     |Mathematics                                 |Eddy resolving simulations in aerospace - Invited paper (Numerical Fluid 2014)                                                                                                                                                  |
|S0307904X16305005|10.1016/j.apm.2016.09.030         |2017    |MATH     |Mathematics                                 |A study on torsional vibration attenuation in automotive drivetrains using absorbers with smooth and non-smooth nonlinearities                                                                                                  |
|S0022249619301373|10.1016/j.jmp.2019.102279         |2019    |MATH     |Mathematics                                 |Fictional narrative as a variational Bayesian method for estimating social dispositions in large groups                                                                                                                         |
|S2468042717300064|10.1016/j.idm.2017.06.005         |2017    |MATH     |Mathematics                                 |National assessment of Canadian pandemic preparedness: Employing InFluNet to identify high-risk areas for inter-wave vaccine distribution                                                                                       |
|S0960077917303661|10.1016/j.chaos.2017.08.037       |2017    |MATH     |Mathematics                                 |Threading a multifractal social psychology through within-organism coordination to within-group interactions: A tale of coordination in three acts                                                                              |
|S2468042717300374|10.1016/j.idm.2018.03.005         |2018    |MATH     |Mathematics                                 |Assessing the utility of the tipping point ratio to monitor HIV treatment programmes in the era of universal access to ART                                                                                                      |
|S1876139917301366|10.1016/j.ecns.2017.11.007        |2018    |MATH     |Mathematics                                 |Video Monitoring a Simulation-Based Quality Improvement Program in Bihar, India                                                                                                                                                 |
|S1063520315000974|10.1016/j.acha.2015.07.002        |2016    |MATH     |Mathematics                                 |Morlet wavelet transforms of heart rate variability for autonomic nervous system activity                                                                                                                                       |
|S2468042716300100|10.1016/j.idm.2016.07.004         |2016    |MATH     |Mathematics                                 |Is it growing exponentially fast? – Impact of assuming exponential growth for characterizing and forecasting epidemics with initial near-exponential growth dynamics                                                            |
|S019567011830272X|10.1016/j.jhin.2018.05.007        |2018    |MEDI     |Medicine                                    |Cost-effectiveness of interventions to improve hand hygiene in healthcare workers in middle-income hospital settings: a model-based analysis                                                                                    |
|S1389945717300370|10.1016/j.sleep.2016.12.026       |2017    |MEDI     |Medicine                                    |Young children with Down syndrome show normal development of circadian rhythms, but poor sleep efficiency: a cross-sectional study across the first 60 months of life                                                           |
|S2210261219306121|10.1016/j.ijscr.2019.10.065       |2019    |MEDI     |Medicine                                    |Acute purulent mediastinitis with sequential bilateral pleural empyema caused by neck trauma: A unique occurrence, a case report                                                                                                |
|S0168827819301126|10.1016/j.jhep.2019.01.035        |2019    |MEDI     |Medicine                                    |The degree of hepatic steatosis associates with impaired cardiac and autonomic function                                                                                                                                         |
|S0895435613003818|10.1016/j.jclinepi.2013.09.004    |2014    |MEDI     |Medicine                                    |In randomization we trust? There are overlooked problems in experimenting with people in behavioral intervention trials                                                                                                         |
|S2210261219301610|10.1016/j.ijscr.2019.03.041       |2019    |MEDI     |Medicine                                    |Surgical management for an infected urachal cyst in an adult: Case report and literature review                                                                                                                                 |
|S2359348215000846|10.1016/j.rppede.2015.06.022      |2016    |MEDI     |Medicine                                    |Validation of questionnaires to assess quality of life related to fecal incontinence in children with anorectal malformations and Hirschsprung's disease                                                                        |
|S2210261219303979|10.1016/j.ijscr.2019.07.015       |2019    |MEDI     |Medicine                                    |Surgical treatment of rare case of scapula osteochondroma in a resource limited setting: A case report                                                                                                                          |
|S2210261217300743|10.1016/j.ijscr.2017.02.003       |2017    |MEDI     |Medicine                                    |Foreign body in the bladder: A case report                                                                                                                                                                                      |
|S2210261219301105|10.1016/j.ijscr.2019.02.045       |2019    |MEDI     |Medicine                                    |Case report of successful management of intraoperative tracheal rupture during thoracoscopic esophageal resection in patient with esophageal cancer                                                                             |
|S221026121930611X|10.1016/j.ijscr.2019.10.064       |2019    |MEDI     |Medicine                                    |Total pelvic exenterative surgery in patients with peritoneal metastases from appendiceal neoplasms. A case series of 2 patients                                                                                                |
|S1808869418306232|10.1016/j.bjorl.2018.08.003       |2018    |MEDI     |Medicine                                    |Anatomical terminology of the internal nose and paranasal sinuses: cross-cultural adaptation to Portuguese                                                                                                                      |
|S147330991730419X|10.1016/S1473-3099(17)30419-X     |2017    |MEDI     |Medicine                                    |Global yellow fever vaccination coverage from 1970 to 2016: an adjusted retrospective analysis                                                                                                                                  |
|S1569199317300905|10.1016/j.jcf.2017.03.007         |2017    |MEDI     |Medicine                                    |Monocyte derived macrophages from CF pigs exhibit increased inflammatory responses at birth                                                                                                                                     |
|S1808869418300879|10.1016/j.bjorl.2018.02.007       |2019    |MEDI     |Medicine                                    |Comparison of long-term functional results between standard supracricoid laryngectomy and modified technique with sternohyoid muscle                                                                                            |
|S0272638616306357|10.1053/j.ajkd.2016.10.025        |2017    |MEDI     |Medicine                                    |A Randomized, Single-Blind, Crossover Trial of Recovery Time in High-Flux Hemodialysis and Hemodiafiltration                                                                                                                    |
|S2452231719300090|10.1016/j.humic.2019.100058       |2019    |MEDI     |Medicine                                    |The effect of having Christmas dinner with in-laws on gut microbiota composition                                                                                                                                                |
|S2210261219302627|10.1016/j.ijscr.2019.05.016       |2019    |MEDI     |Medicine                                    |Supralevator abscess: New treatment for an uncommon aetiology: Case report                                                                                                                                                      |
|S221026121830542X|10.1016/j.ijscr.2018.11.035       |2019    |MEDI     |Medicine                                    |Bilateral cystic lesions of the chest wall: Presentation of scapulothoracic bursitis                                                                                                                                            |
|S2352187216300213|10.1016/j.bonr.2016.05.006        |2016    |MEDI     |Medicine                                    |Effect of micro-computed tomography voxel size and segmentation method on trabecular bone microstructure measures in mice                                                                                                       |
|S1053811917302197|10.1016/j.neuroimage.2017.03.011  |2017    |NEUR     |Neuroscience                                |Comparing GABA-dependent physiological measures of inhibition with proton magnetic resonance spectroscopy measurement of GABA using ultra-high-field MRI                                                                        |
|S0378595519303673|10.1016/j.heares.2019.107870      |2020    |NEUR     |Neuroscience                                |Intravenously delivered aminoglycoside antibiotics, tobramycin and amikacin, are not ototoxic in mice                                                                                                                           |
|S1053811916301112|10.1016/j.neuroimage.2016.05.003  |2016    |NEUR     |Neuroscience                                |Towards motion insensitive EEG-fMRI: Correcting motion-induced voltages and gradient artefact instability in EEG using an fMRI prospective motion correction (PMC) system                                                       |
|S1053811919309267|10.1016/j.neuroimage.2019.116335  |2020    |NEUR     |Neuroscience                                |Multi-site harmonization of 7 tesla MRI neuroimaging protocols                                                                                                                                                                  |
|S105381191501037X|10.1016/j.neuroimage.2015.11.015  |2016    |NEUR     |Neuroscience                                |Bayesian model reduction and empirical Bayes for group (DCM) studies                                                                                                                                                            |
|S1053811914006338|10.1016/j.neuroimage.2014.07.050  |2014    |NEUR     |Neuroscience                                |Global intravascular and local hyperoxia contrast phase-based blood oxygenation measurements                                                                                                                                    |
|S0896627317306384|10.1016/j.neuron.2017.07.016      |2017    |NEUR     |Neuroscience                                |RNA Docking and Local Translation Regulate Site-Specific Axon Remodeling In Vivo                                                                                                                                                |
|S1053811916000616|10.1016/j.neuroimage.2016.01.046  |2016    |NEUR     |Neuroscience                                |Bingham-NODDI: Mapping anisotropic orientation dispersion of neurites using diffusion MRI                                                                                                                                       |
|S1053811916303901|10.1016/j.neuroimage.2016.08.012  |2016    |NEUR     |Neuroscience                                |Atypical right hemisphere response to slow temporal modulations in children with developmental dyslexia                                                                                                                         |
|S1053811915009660|10.1016/j.neuroimage.2015.10.055  |2016    |NEUR     |Neuroscience                                |Brain basis of communicative actions in language                                                                                                                                                                                |
|S1053811915003614|10.1016/j.neuroimage.2015.04.061  |2015    |NEUR     |Neuroscience                                |Brain structure correlates of emotion-based rash impulsivity                                                                                                                                                                    |
|S0301008219300826|10.1016/j.pneurobio.2019.101692   |2019    |NEUR     |Neuroscience                                |The activity of the prelimbic cortex in rats is enhanced during the cooperative acquisition of an instrumental learning task                                                                                                    |
|S001448861830606X|10.1016/j.expneurol.2018.10.011   |2019    |NEUR     |Neuroscience                                |Neurogenesis changes and the fate of progenitor cells after subarachnoid hemorrhage in rats                                                                                                                                     |
|S0306452213010373|10.1016/j.neuroscience.2013.12.021|2014    |NEUR     |Neuroscience                                |Proliferation, differentiation and amyloid-β production in neural progenitor cells isolated from TgCRND8 mice                                                                                                                   |
|S1053811918305573|10.1016/j.neuroimage.2018.06.050  |2018    |NEUR     |Neuroscience                                |GridLoc: An automatic and unsupervised localization method for high-density ECoG grids                                                                                                                                          |
|S0014488616301157|10.1016/j.expneurol.2016.05.008   |2016    |NEUR     |Neuroscience                                |Cognitive training modifies disease symptoms in a mouse model of Huntington's disease                                                                                                                                           |
|S1053811915005558|10.1016/j.neuroimage.2015.06.050  |2015    |NEUR     |Neuroscience                                |The human voice areas: Spatial organization and inter-individual variability in temporal and extra-temporal cortices                                                                                                            |
|S1878929318301336|10.1016/j.dcn.2019.100681         |2019    |NEUR     |Neuroscience                                |Mind the gap: A review and recommendations for statistically evaluating Dual Systems models of adolescent risk behavior                                                                                                         |
|S0301008219301145|10.1016/j.pneurobio.2019.101691   |2019    |NEUR     |Neuroscience                                |State estimation in posterior parietal cortex: Distinct poles of environmental and bodily states                                                                                                                                |
|S0168010219303207|10.1016/j.neures.2019.11.002      |2019    |NEUR     |Neuroscience                                |X-irradiation of developing hippocampal neurons causes changes in neuron population phenotypes, dendritic morphology and synaptic protein expression in surviving neurons at maturity                                           |
|S1055329016301042|10.1016/j.jana.2016.07.004        |2016    |NURS     |Nursing                                     |Easy, Faster, and Not Bloody: Providers' Perceptions on PrePex™ in South Africa                                                                                                                                                 |
|S1755599X1630180X|10.1016/j.ienj.2017.05.002        |2017    |NURS     |Nursing                                     |Piloting a global mentorship initiative to support African emergency nurses                                                                                                                                                     |
|S0884217515315665|10.1111/1552-6909.12469           |2014    |NURS     |Nursing                                     |An interprofessional quality improvement project to implement maternal/infant skin-to-skin contact during cesarean delivery                                                                                                     |
|S2214139115000165|10.1016/j.ijans.2015.07.002       |2015    |NURS     |Nursing                                     |Mainstreaming Kenya-Nursing Process in clinical settings: The case of Kenya                                                                                                                                                     |
|S0020748917300949|10.1016/j.ijnurstu.2017.04.008    |2017    |NURS     |Nursing                                     |Implementing monitoring technologies in care homes for people with dementia: A qualitative exploration using Normalization Process Theory                                                                                       |
|S1462388916300278|10.1016/j.ejon.2016.03.009        |2016    |NURS     |Nursing                                     |Feasibility of a mobile and web-based intervention to support self-management in outpatients with cancer pain                                                                                                                   |
|S0029655414000517|10.1016/j.outlook.2014.03.001     |2014    |NURS     |Nursing                                     |The patient-centered outcomes research institute (PCORI): Information for academic nursing                                                                                                                                      |
|S0020748915001601|10.1016/j.ijnurstu.2015.05.001    |2015    |NURS     |Nursing                                     |Reducing conflict and containment rates on acute psychiatric wards: The Safewards cluster randomised controlled trial                                                                                                           |
|S0020748915002308|10.1016/j.ijnurstu.2015.07.008    |2015    |NURS     |Nursing                                     |Professional perspectives on service user and carer involvement in mental health care planning: A qualitative study                                                                                                             |
|S0020748919302949|10.1016/j.ijnurstu.2019.103487    |2020    |NURS     |Nursing                                     |Nursing workload, nurse staffing methodologies and tools: A systematic scoping review and discussion                                                                                                                            |
|S0020748919300367|10.1016/j.ijnurstu.2019.02.005    |2019    |NURS     |Nursing                                     |Cognitive impairment is independently associated with mortality, extended hospital stays and early readmission of older people with emergency hospital admissions: A retrospective cohort study                                 |
|S002074891600064X|10.1016/j.ijnurstu.2016.02.001    |2016    |NURS     |Nursing                                     |The effect of nurses' preparedness and nurse practitioner status on triage call management in primary care: A secondary analysis of cross-sectional data from the ESTEEM trial                                                  |
|S1462388919300183|10.1016/j.ejon.2019.02.003        |2019    |NURS     |Nursing                                     |Haematology nurses' perspectives of their patients' places of care and death: A UK qualitative interview study                                                                                                                  |
|S2214139115000177|10.1016/j.ijans.2015.07.003       |2015    |NURS     |Nursing                                     |Assessing nurses' knowledge levels in the nutritional management of diabetes                                                                                                                                                    |
|S2214139116300282|10.1016/j.ijans.2016.09.002       |2016    |NURS     |Nursing                                     |Healthcare-seeking behaviour and management of type 2 diabetes: From Ugandan traditional healers’ perspective                                                                                                                   |
|S0020748917300299|10.1016/j.ijnurstu.2017.02.001    |2017    |NURS     |Nursing                                     |Interventions and working relationships of voluntary organisations for diabetes self-management: A cross-national study                                                                                                         |
|S0882596318305098|10.1016/j.pedn.2019.02.036        |2019    |NURS     |Nursing                                     |Parents Experiences Raising a Child with Food Allergy; A Qualitative Review                                                                                                                                                     |
|S1462388918300802|10.1016/j.ejon.2018.06.002        |2018    |NURS     |Nursing                                     |A conversation approach based on shared goal-setting and shared decision-making for nurses in cancer aftercare: A developmental study                                                                                           |
|S1355184119300663|10.1016/j.jnn.2019.07.002         |2019    |NURS     |Nursing                                     |The knowledge and learning needs of health professionals in providing support for parents of premature babies at home: A mixed-methods study                                                                                    |
|S1462388914001355|10.1016/j.ejon.2014.08.006        |2015    |NURS     |Nursing                                     |Diet and physical activity intervention in colorectal cancer survivors: A feasibility study                                                                                                                                     |
|S2211379719322508|10.1016/j.rinp.2019.102711        |2019    |PHYS     |Physics and Astronomy                       |Effect of slit width on surface plasmon resonance                                                                                                                                                                               |
|S2211379718301566|10.1016/j.rinp.2018.02.067        |2018    |PHYS     |Physics and Astronomy                       |Experimental analysis for heat transfer of nanofluid with wire coil turbulators in a concentric tube heat exchanger                                                                                                             |
|S0003682X15001802|10.1016/j.apacoust.2015.06.014    |2015    |PHYS     |Physics and Astronomy                       |Prediction of airborne radiated noise from lightly loaded lubricated meshing gear teeth                                                                                                                                         |
|S0168900213017646|10.1016/j.nima.2013.12.051        |2014    |PHYS     |Physics and Astronomy                       |The practical use of an interactive visualization and planning tool for intervention planning in particle accelerator environments with ionizing radiation                                                                      |
|S2211379719314664|10.1016/j.rinp.2019.102529        |2019    |PHYS     |Physics and Astronomy                       |Structural, morphological, antimicrobial, and in vitro photodynamic therapeutic assessments of novel Zn+2-substituted cobalt ferrite nanoparticles                                                                              |
|S0168900214013953|10.1016/j.nima.2014.11.081        |2015    |PHYS     |Physics and Astronomy                       |Another look at confidence intervals: Proposal for a more relevant and transparent approach                                                                                                                                     |
|S2211379718302900|10.1016/j.rinp.2018.03.004        |2018    |PHYS     |Physics and Astronomy                       |Study of the electrical and thermal performances of photovoltaic thermal collector-compound parabolic concentrated                                                                                                              |
|S221137971731313X|10.1016/j.rinp.2017.09.043        |2017    |PHYS     |Physics and Astronomy                       |Elastic, thermodynamic and optical behavior of V2AC (A = Al, Ga) MAX phases                                                                                                                                                     |
|S0168900214014867|10.1016/j.nima.2014.12.044        |2015    |PHYS     |Physics and Astronomy                       |Micro-channel plates and vacuum detectors                                                                                                                                                                                       |
|S221137971832240X|10.1016/j.rinp.2018.11.013        |2018    |PHYS     |Physics and Astronomy                       |Investigation of highly birefringent and highly nonlinear Hexa Sectored PCF with low confinement loss                                                                                                                           |
|S0168900215016010|10.1016/j.nima.2015.12.030        |2016    |PHYS     |Physics and Astronomy                       |Characterization of gallium arsenide X-ray mesa p-i-n photodiodes at room temperature                                                                                                                                           |
|S016890021401482X|10.1016/j.nima.2014.12.040        |2015    |PHYS     |Physics and Astronomy                       |Quality control of the TSV multi-pixel photon counter arrays, and modules for the external plate of EndoTOF-PET ultrasound detector                                                                                             |
|S2211379718313317|10.1016/j.rinp.2018.08.039        |2018    |PHYS     |Physics and Astronomy                       |Dual photoacoustic monitoring in laser ablation synthesis of silver nanoparticles to find in situ their fluence threshold formation                                                                                             |
|S0041624X13003351|10.1016/j.ultras.2013.11.011      |2014    |PHYS     |Physics and Astronomy                       |Shear horizontal (SH) ultrasound wave propagation around smooth corners                                                                                                                                                         |
|S2211379718332649|10.1016/j.rinp.2019.02.053        |2019    |PHYS     |Physics and Astronomy                       | Recycled photocatalyst and available photodetector based on ternary Bi 6 Mo 2 O 15 sub-microcrystals                                                                                                                           |
|S0003682X13002946|10.1016/j.apacoust.2013.12.013    |2014    |PHYS     |Physics and Astronomy                       |Using transient and steady-state SEA to assess potential errors in the measurement of structure-borne sound power input from machinery on coupled reception plates                                                              |
|S0969804317303044|10.1016/j.apradiso.2017.08.002    |2018    |PHYS     |Physics and Astronomy                       |Characterisation of an ultra low-background point contact HPGe well-detector for an underground laboratory                                                                                                                      |
|S2211379718331668|10.1016/j.rinp.2019.01.096        |2019    |PHYS     |Physics and Astronomy                       |Optimized dye-sensitized solar cells: A comparative study with different dyes, mordants and construction parameters                                                                                                             |
|S0168900213017208|10.1016/j.nima.2013.12.029        |2014    |PHYS     |Physics and Astronomy                       |Experimental and theoretical progress of linear collider final focus design and ATF2 facility                                                                                                                                   |
|S2211379716300742|10.1016/j.rinp.2016.10.010        |2016    |PHYS     |Physics and Astronomy                       |Linear and nonlinear optical properties of Gd3+ doped zinc borotellurite glasses for all-optical switching applications                                                                                                         |
|S0022096516300625|10.1016/j.jecp.2016.06.005        |2016    |PSYC     |Psychology                                  |“Model age-based” and “copy when uncertain” biases in children's social learning of a novel task                                                                                                                                |
|S1053810018302514|10.1016/j.concog.2018.07.011      |2018    |PSYC     |Psychology                                  |Response to Ruby et al: On a ‘failed’ attempt to manipulate conscious perception with transcranial magnetic stimulation to prefrontal cortex                                                                                    |
|S0272494419302154|10.1016/j.jenvp.2019.101368       |2019    |PSYC     |Psychology                                  |Intentions, efficacy, and norms: The impact of different self-regulatory cues on reducing engine idling at long wait stops                                                                                                      |
|S0163638314000411|10.1016/j.infbeh.2014.04.007      |2014    |PSYC     |Psychology                                  |Comparing methods for measuring peak look duration: Are individual differences observed on screen-based tasks also found in more ecologically valid contexts?                                                                   |
|S1469029218305181|10.1016/j.psychsport.2019.04.007  |2019    |PSYC     |Psychology                                  |Longitudinal associations between parents’ motivations to exercise and their moderate-to-vigorous physical activity                                                                                                             |
|S0022096516302909|10.1016/j.jecp.2016.12.003        |2017    |PSYC     |Psychology                                  |Online recruitment and testing of infants with Mechanical Turk                                                                                                                                                                  |
|S1755458616300974|10.1016/j.emospa.2017.05.005      |2018    |PSYC     |Psychology                                  |Skywalking in the city: Glass platforms and the architecture of vertigo                                                                                                                                                         |
|S1053810017302775|10.1016/j.concog.2017.09.009      |2017    |PSYC     |Psychology                                  |Learning to infer the time of our actions and decisions from their consequences                                                                                                                                                 |
|S0191886916310352|10.1016/j.paid.2016.10.007        |2017    |PSYC     |Psychology                                  |From Likert scales to images: Validating a novel creativity measure with image based response scales                                                                                                                            |
|S0022096515002891|10.1016/j.jecp.2015.11.013        |2016    |PSYC     |Psychology                                  |Labels constructively shape object categories in 10-month-old infants                                                                                                                                                           |
|S0163638314000939|10.1016/j.infbeh.2014.09.005      |2014    |PSYC     |Psychology                                  |Consistency of maternal cognitions and principles across the first five months following preterm and term deliveries                                                                                                            |
|S2352250X18300988|10.1016/j.copsyc.2018.07.006      |2019    |PSYC     |Psychology                                  |Non-coding genetic variation shaping mental health                                                                                                                                                                              |
|S0163638314000551|10.1016/j.infbeh.2014.06.002      |2014    |PSYC     |Psychology                                  |Mothers who are securely attached in pregnancy show more attuned infant mirroring 7 months postpartum                                                                                                                           |
|S0191886919306786|10.1016/j.paid.2019.109738        |2020    |PSYC     |Psychology                                  |The General Factor of Personality and daily social experiences: Evidence for the social effectiveness hypothesis                                                                                                                |
|S2352250X16302007|10.1016/j.copsyc.2017.06.010      |2017    |PSYC     |Psychology                                  |Discovering cultural differences (and similarities) in facial expressions of emotion                                                                                                                                            |
|S0163638318301346|10.1016/j.infbeh.2019.101340      |2019    |PSYC     |Psychology                                  |Infants’ perception of goal-directed actions: A multi-lab replication reveals that infants anticipate paths and not goals                                                                                                       |
|S0022096515002325|10.1016/j.jecp.2015.09.028        |2016    |PSYC     |Psychology                                  |Theory of mind and executive function during middle childhood across cultures                                                                                                                                                   |
|S0163638315301272|10.1016/j.infbeh.2016.06.005      |2016    |PSYC     |Psychology                                  |Exploring early communicative behaviours: A fine-grained analysis of infant shows and gives                                                                                                                                     |
|S016363831730053X|10.1016/j.infbeh.2017.05.004      |2017    |PSYC     |Psychology                                  |Affective facial expression in sub-clinically depressed and non-depressed mothers during contingent and non-contingent face-to-face interactions with their infants                                                             |
|S0272494415300487|10.1016/j.jenvp.2015.11.008       |2016    |PSYC     |Psychology                                  |Empowering interventions to promote sustainable lifestyles: Testing the habit discontinuity hypothesis in a field experiment                                                                                                    |
|S0742051X17302858|10.1016/j.tate.2017.02.013        |2017    |SOCI     |Social Sciences                             |Developing entrepreneurship in primary schools. The Mexican experience of “My first enterprise: Entrepreneurship by playing”                                                                                                    |
|S0738059314001126|10.1016/j.ijedudev.2014.11.004    |2015    |SOCI     |Social Sciences                             |The early grade reading assessment (EGRA): Its theoretical foundation, purpose, and limitations                                                                                                                                 |
|S027753951730420X|10.1016/j.wsif.2017.10.005        |2017    |SOCI     |Social Sciences                             |Women's rights to land and communal forest tenure: A way forward for research and policy agenda in Latin America                                                                                                                |
|S0967070X16301469|10.1016/j.tranpol.2016.07.012     |2016    |SOCI     |Social Sciences                             |Watching the Swiss: A network approach to rural and exurban public transport                                                                                                                                                    |
|S104026081630034X|10.1016/j.alcr.2016.06.001        |2016    |SOCI     |Social Sciences                             |Residential mobility across the life course: Continuity and change across three cohorts in Britain                                                                                                                              |
|S0016718518300022|10.1016/j.geoforum.2018.01.002    |2018    |SOCI     |Social Sciences                             |Profit, reputation and ‘doing the right thing’: Convention theory and the problem of food waste in the UK retail sector                                                                                                         |
|S0016718517301082|10.1016/j.geoforum.2017.05.002    |2019    |SOCI     |Social Sciences                             |With-against-and-beyond the human right to water                                                                                                                                                                                |
|S0743016716302790|10.1016/j.jrurstud.2017.06.022    |2017    |SOCI     |Social Sciences                             |Impacts of extension access and cooperative membership on technology adoption and household welfare                                                                                                                             |
|S0016718517303421|10.1016/j.geoforum.2017.12.006    |2018    |SOCI     |Social Sciences                             |Exploring the spatialities of technological and user re-scripting: The case of decision support tools in UK agriculture                                                                                                         |
|S0967070X1530041X|10.1016/j.tranpol.2015.08.002     |2016    |SOCI     |Social Sciences                             |Commuting practices: New insights into modal shift from theories of social practice                                                                                                                                             |
|S026137941830146X|10.1016/j.electstud.2018.04.011   |2018    |SOCI     |Social Sciences                             |Intermedia agenda setting in personalized campaigns: How news media influence the importance of leaders                                                                                                                         |
|S0742051X18314100|10.1016/j.tate.2019.07.005        |2019    |SOCI     |Social Sciences                             |Transformative agency in teacher education: Fostering professional digital competence                                                                                                                                           |
|S0261379418302257|10.1016/j.electstud.2018.10.005   |2019    |SOCI     |Social Sciences                             |Do citizens make inferences from political candidate characteristics when aiming for substantive representation?                                                                                                                |
|S0016718515300385|10.1016/j.geoforum.2016.02.008    |2016    |SOCI     |Social Sciences                             |Imagining global work: Producing understandings of difference in 'easy Asia'                                                                                                                                                    |
|S0305900614000361|10.1016/j.progress.2013.05.002    |2014    |SOCI     |Social Sciences                             |Delivering affordable workspace: Perspectives of developers and workspace providers in London                                                                                                                                   |
|S0016718515000500|10.1016/j.geoforum.2015.02.014    |2015    |SOCI     |Social Sciences                             |Articulating an Indian diaspora in South Africa: The consulate general of India, diaspora associations and practices of collaboration                                                                                           |
|S0740624X17303271|10.1016/j.giq.2018.03.002         |2018    |SOCI     |Social Sciences                             |Factors influencing e-diplomacy implementation: Exploring causal relationships using interpretive structural modelling                                                                                                          |
|S0967070X17305000|10.1016/j.tranpol.2018.11.003     |2019    |SOCI     |Social Sciences                             |Transportation resilience to climate change and extreme weather events – Beyond risk and robustness                                                                                                                             |
|S0277539515301783|10.1016/j.wsif.2016.08.004        |2017    |SOCI     |Social Sciences                             |Challenges for women's participation in communal forests: Experience from Nicaragua's in digenous territories                                                                                                                   |
|S1353829216305056|10.1016/j.healthplace.2016.11.013 |2017    |SOCI     |Social Sciences                             |Associations between perceived neighbourhood problems and quality of life in older adults with and without osteoarthritis: Results from the Hertfordshire Cohort Study                                                          |
